우주야구 1 구현
Programmers-Hyune-c/cosmic-baseball-init pull request #14
Opened 2022-12-21 12:55 UTC by yonggyujeong

SpecialHitterResult : bullseye_strike, bullseyeBall, homerun 추가
ControllerAdvice 를 이용하여 Exception 처리를 간단하게 했는데, 예외 처리에 좀 더 공을 들여야 할까요?

2022-12-21 13:55 UTC, Hyune-c requested changes
HitterResult 와 SpecialHitterResult 는 다른 개념일까요?
저는 둘다 hitting 의 결과라고 생각됩니다.

2022-12-21 13:55 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/ControllerExceptionHandler.java
> +    }
- 에러 메시지가 없는 에러는 로그에 어떻게 찍힐까요?
    - 에러 메시지가 없는 에러를 생성하는 테스트 케이스를 만들면 좋을 것 같습니다.
- Exception 전체를 핸들링하는 것은 너무 크지 않을까요? 
    - 만약 한다고 하더라도 그것이 BAD_REQUEST 에 적절할까요?
- `@ResponseStatus` 를 활용해볼 수 있지 않을까요?

2022-12-21 13:55 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/GameController.java
>      }
사용자가 hitting 이라는 api 호출시 `종료된 게임에 hitting 을 하면 초기화 되는 것` 을 알고 있나요?

2022-12-21 13:55 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/lv1/Lv1HitterGameService.java
> +    public boolean isWhenScoreInit(String hittingResult){
저는 시그니처를 보고는 이 메서드가 무엇인지 모르겠습니다.

2022-12-21 13:55 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/service/lv1/Lv1HitterGameServiceTest.java
> +                dynamicTest("점수 초기화", () -> {
`nit` 점수를 초기화하는 것 보다는 새로운 테스트 시나리오로 분리하는 것이 좋다고 생각합니다.

2022-12-22 03:43 UTC, yonggyujeong commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/GameController.java
>      }
음.. 만약 점수 초기화 로직을 hitting api에서 분리 시키면 strike out 이나 hit 등 한 타석이 끝난 후에 점수를 바로 초기화 시킬 수 없지 않나요? 로직 수정이 아니라 api명을 사용자가 이해하기 쉽도록 수정하면 되는 것일 까요?

2022-12-22 05:31 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/GameController.java
>      }
종료된 게임에 hitting 을 시도하면 `이미 종료된 게임입니다.` 라는 것을 명시적으로 알려주는 것은 어떨까요?
그리고 프론트 개발자가 게임을 초기화할 수 있는 api 를 별도로 만들어줄 수 있겠죠.

조금의 방어로직을 추가하자면, `종료되지 않은 게임은 초기화할 수 없다.` 가 들어가도 좋구요.
지금의 로직대로라면, `종료된 게임의 상태를 보고 싶은 사용자 (재시작을 원하지 않음)` 의 니즈를 만족시킬 수 없습니다.

---

지금의 api 설계에서 resource 는 game 으로 보입니다.
`game 의 상태를 변화시키는 행위` 에 대해 고민해주세요.

2022-12-25 13:27 UTC, Hyune-c requested changes

2022-12-25 13:27 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/service/lv1/Lv1HitterGameServiceTest.java
> +                    method1.invoke(lv1HitterGameService, result3);
private 메서드를 테스트하기 위해 리플렉션을 사용하는 것에 대해 어떤 생각을 가지고 계신가요?

2022-12-25 13:27 UTC, Hyune-c commented on src/main/resources/message.yml
> +  score-init: "점수가 초기화 되었습니다"
`nit` 꽤 괜찮은 방법이지만, 국제화를 고려하지 않는 프로젝트라면 그냥 상수로서 관리하는 것도 나쁘지 않다고 생각합니다.

2022-12-25 13:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/SpecialHitterResult.java
> +    }
- null 을 반환하는 것에 대해 어떻게 생각하시나요?
- 메서드가 throw exception 한다는 것에 대해 어떻게 생각하시나요?

2022-12-25 13:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/SpecialHitterResult.java
> +    }
`nit` stream 을 활용하면 조금 더 깔끔해질 것 같습니다.

2022-12-25 13:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/HitterResult.java
> +        throw new Exception("findHitterResultByPitchResult error");
`nit` 
continue 활용은 꽤 위험한 방법입니다.
stream 을 활용하면 조금 더 깔끔한 코딩이 가능할 것 같습니다.

2022-12-25 13:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/GameController.java
> +    //FIXME 테스트용, 에러메세지를 반환하지 않는 에러
`nit` fixme 와 todo 를 구분해서 사용하는 것도 좋지만, 지금 정도 규모라면 하나로 통일하는 것도 방법입니다.

2022-12-26 14:21 UTC, yonggyujeong reviewed
코드리뷰에 대한 댓글

2022-12-26 14:21 UTC, yonggyujeong commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/HitterResult.java
> +        throw new Exception("findHitterResultByPitchResult error");
stream에 익숙하지 않아서 잘 사용하지 않고 있었는데, stream 활용법을 익혀보겠습니다. 인터넷을 찾아보니 스트림에 관한 글들은 주로 effective 자바 라는 책을 인용하는 것을 느껴서, 해당 책을 구매하려고 합니다. 괜찮은 선택일까요?

2022-12-26 14:21 UTC, yonggyujeong commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/SpecialHitterResult.java
> +    }
- null 반환
조건문에 해당하지 않을 시 , 제 코드에서는 처음에는 예외반환을 하다가 정상 상황인데 예외를 반환하는 것이 예외 처리 할 때 어떻게 처리할지 애매하다는 것을 깨닫고, 이번 함수에는 null을 반환하도록 해 보았습니다. 하지만 인터넷을 찾아보니, `Optional` 이라는 타입을 반환하는 것이 옳은 선택인 것 같습니다.
[참고한 자료](https://dundung.tistory.com/187)

- throw exception
정말 예외적인 상황에서만 쓰도록 변경하는 것이 좋을 것 같습니다.

2022-12-26 14:21 UTC, yonggyujeong commented on src/test/java/com/hyunec/cosmicbaseballinit/service/lv1/Lv1HitterGameServiceTest.java
> +                    method1.invoke(lv1HitterGameService, result3);
리플렉션을 사용하니, 컴파일시에 에러를 잡을 수 없고, 이는 코드가 변경되었을 때 에러를 파악하기 쉽지 않은 것 같습니다.
아울러 조사를 해보니까, private 메서드에 대해서는 테스트를 진행하지 않는 것이 맞고, public 메서드로 충분히 테스트 가능하게 설계가 되어야 한다고 조사했는데 맞을까요?
[참고한 자료](https://mangkyu.tistory.com/235)

2022-12-26 14:21 UTC, yonggyujeong commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/ControllerExceptionHandler.java
> +    }
- 예외 처리 관련한 부분은 더 공부를 해서 수정해 보도록 하겠습니다.

2022-12-26 14:34 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/HitterResult.java
> +        throw new Exception("findHitterResultByPitchResult error");
네. 이펙티브 자바는 꼭 구입하시어 1년에 한번씩 읽어보시기를 추천합니다.

2022-12-26 14:34 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/SpecialHitterResult.java
> +    }
### null 반환
> 네. 답변주신 내용이 전반적으로 맞는 내용입니다.
- `옳은 선택` 보다는 `좋은 선택` 이라는 표현이 좀 더 완곡한 표현이라고 생각합니다.
- java 는 nullsafe 하지 않기에 `Optional`로 보완하고 있습니다. 이것은 언어적인 문제이기에 아쉬움이 있습니다.
    - 하지만 조금 더 인사이트를 얻으시기를 기대하며 키워드를 드립니다.
    - `토니 호어` `10억 달러짜리 실수` `kotlin 에서는 어떻게 해결하고 있는가?`

2022-12-26 14:34 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/service/lv1/Lv1HitterGameServiceTest.java
> +                    method1.invoke(lv1HitterGameService, result3);
> 리플렉션을 사용하니, 컴파일시에 에러를 잡을 수 없고, 이는 코드가 변경되었을 때 에러를 파악하기 쉽지 않은 것 같습니다.

네 그렇습니다.

> 아울러 조사를 해보니까, private 메서드에 대해서는 테스트를 진행하지 않는 것이 맞고

- `진행하지 않는 것이 맞다.` 라는 표현은 너무 단정적입니다만, 저도 같은 의견이긴 합니다.
- private method 가 독립적인 테스트가 필요할 정도라면 `비즈니스 로직이 충분히 분리된 것인지를 의심`해야 될 것입니다.

2022-12-26 14:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/vo/HitterResult.java
> +        throw new Exception("findHitterResultByPitchResult error");
```suggestion
return Arrays.stream(HitterResult.values())
                .filter(hitterResult -> hitterResult.pitchResult.equals(pitchResult))
                .findFirst()
                .orElseThrow(() -> new Exception("findHitterResultByPitchResult error"));
```

스트림으로 정리하면 위처럼 될 수 있을 것 같습니다.

2022-12-29 04:48 UTC, Hyune-c approved these changes

2022-12-29 04:48 UTC, Hyune-c commented on build.gradle
> +    implementation 'com.google.code.findbugs:jsr305:3.0.2'
`javax.annotation.meta.When 에러 해결을 위한 gradle dependency 추가` 로 표현하셨는데 정작 코드에서 `when` 이 쓰이는 곳이 없습니다. 
어떤 의도의 dependency 인가요?

2022-12-29 04:48 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/service/lv1/Lv1HitterGameServiceUnitTest.java
> +    }
`nit` test 코드에서의 주석 처리라면 `@Ignored` 를 활용하시는 것을 추천합니다.

2023-01-01 06:54 UTC, merged