리뷰 반영 및 영속성 레이어 분리
Programmers-Hyune-c/cosmic-baseball-init pull request #16
Opened 2023-01-05 14:29 UTC by yonggyujeong

일반 야구2 구현 중, 영속성 영역의 분리가 선행되지 않으니, 난이도가 너무 높아지는것 같아서, 구현한 것들 제껴두고 우선 approve된 커밋에서 영속성 영역만 분리하여 푸시하였습니다.

2023-01-06 05:53 UTC, Hyune-c requested changes
구조 개선이라는 점에서 좋은 시도 입니다.

- 점점 하나의 service 에 메서드가 많아지고 있습니다.
    - facade 패턴과 srp 에 대해 공부해주세요.

2023-01-06 05:53 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/HitterGameProbabilitiesDao.java
> +    }
`nit` filter 를 활용하면 좀 더 간결하게 할 수 있을 것 같습니다. 하지만 명시성을 우선한다는 점이라면 지금도 좋습니다.

2023-01-06 05:53 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/HitterGameProbabilitiesDao.java
> +    }
java 에서는 잘 지켜지지 않지만 불변성에 대해 고민해주세요.

2023-01-06 05:53 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/lv1/HitterGameService.java
>      }
메서드 내에서 vo 를 활용하지 않는건가요?

2023-01-06 14:53 UTC, yonggyujeong commented on src/main/java/com/hyunec/cosmicbaseballinit/service/lv1/HitterGameService.java
>      }
save()의 파라메터로 넣어야하는데 넣지 않았네요.. 다시 넣어서 push 했습니다 감사합니다

2023-01-07 05:28 UTC, Hyune-c approved these changes

2023-01-07 07:17 UTC, merged