일반야구 2 구현완료
Programmers-Hyune-c/cosmic-baseball-init pull request #17
Opened 2023-01-09 03:41 UTC by yonggyujeong

PR을 쪼개서 보내면 완성하는데 기간이 더 오래 걸릴 것 같고 과정도 끝났는데 빨리 마무리 짓는게 좋을것 같아서.. 우선 구현을 완료하고 PR을 보냅니다. PR의 규모가 큰건.. 죄송합니다

### RoundGame의 구성
- RoundGame 따로 폴더를 나누었습니다.
- HitterGame 도 따로 폴더를 나누어야 하나 그러면 PR안의 수정된 양이 너무 많을 것 같아서 하지 않았습니다
- RoundGame에 Controller, domain, persistence 세 영역으로 나누어서 구현했습니다.

### HitterGameController 변경
이전 HitterGame의 Controller는 HitterGameInterface로 변경했습니다.
RoundGame에서 이 Interface를 이용하는 형식입니다.

### RoundGame기능 구성
- setting : 게임 세팅(Pitch 결과 반환 확률 세팅)
- hitting : Hitting 진행
- getScore : 진행완료된 HitterGame과 진행중인 HitterGame의 결과값 + Out, 득점수 반환
- init : 게임 초기화

2023-01-09 04:09 UTC, Hyune-c requested changes

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/HitterGameInterfaceImpl.java
> +public class HitterGameInterfaceImpl implements HitterGameInterface{
`nit` interface 와 impl 의 관계라면 보통 구현체는 interface 를 생략합니다.
`HitterGameInterface` - `HitterGameImpl`

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/HitterGameInterfaceImpl.java
> +    public String hitting(HittingParamVo hittingParamVo) throws Exception {
param 이라는 단어는 생략할 수 있을 것 같습니다.
`gameSetting` 메서드에서 사용하는 vo 와도 네이밍의 일관성이 맞지 않아요.

req/request/query/command 등의 접미사로 일관성을 가져갈 수 있을 것 같습니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/HitterGameInterfaceImpl.java
> +    public String gameSetting(PitchProbabilitySettingVo pitchProbabilitySettingVo){
override 가 누락된 메서드들이 보입니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/HitterGameInterfaceImpl.java
> +    public Boolean isHitterGameEnd() {
```suggestion
    public Boolean isEnd() {
```
`nit` 인터페이스를 활용하고 클래스 네이밍에 `HitterGame` 이 이미 들어가 있기에 생략하는 것도 방법입니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/HitterGameProbabilitiesDao.java
> +    private PitchResultProbabilities pitchResultProbabilities = new PitchResultProbabilities(new HashMap<>());
👍

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/controller/RoundGameController.java
> +    public String hitting() throws Exception {
`throws Exception` 을 제거할 수 있는 방법은 없을까요?

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/controller/RoundGameInterfaceImpl.java
> +    // 확률 랜덤값을 클라이언트로 부터 입력 받음
`nit` 기능 설명을 위한 주석이라면 javadoc 형태를 추천합니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/Base.java
> +    private final Queue<Integer> bases;
👍

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +@ToString
toString 의 위험성을 알고 계신가요?

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +public class HitterGameResultList {
`nit` 
일급 컬렉션을 의도하신 것이라면 구체적인 자료구조 명시는 추천하지 않습니다.
list 라는 표현이 자료구조와 별개라고 생각할 수도 있지만, 개발자라면 list 를 보고 자료구조를 먼저 떠올리기 때문입니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +    }
일급 컬렉션을 의도하신 것이라면 immutable 반환을 권장합니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/Round.java
> +    }
`nit` 
아웃이나 점수는 줄어들 수 없는 개념이므로 plus 가 없어도 된다고 생각합니다.
- `out 이라는 메세지` 를 전달합니다.

2023-01-09 04:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/service/BaseService.java
> +    }
base 에 대한 기능을 응집시키려는 목적이라면 base 와 득점은 분리되어야 한다고 생각합니다.
`진루(주루) 의 결과로 득점`이 되는 로직은 base 를 포함하는 애그리거트에서 이루어져야 된다고 생각합니다.

2023-01-10 15:28 UTC, yonggyujeong reviewed
리뷰 감사드립니다. 궁금한 점이 하나 있는데, roundGame의 구조가 만들면서 배우는 클린아키텍쳐를 읽으면서 해당 내용을 조금 반영을 한 것인데.. 혹시 구조가 조금 어색한가요? 현업의 관점에서는 의견이 어떠하신지 궁금합니다

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/HitterGameInterfaceImpl.java
> +    public String gameSetting(PitchProbabilitySettingVo pitchProbabilitySettingVo){
추가하였습니다. 감사합니다.

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/HitterGameInterfaceImpl.java
> +    public String hitting(HittingParamVo hittingParamVo) throws Exception {
네이밍 일관성에 대해 나름의 규칙을 만들어야 겠습니다. 감사합니다

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/controller/RoundGameController.java
> +    public String hitting() throws Exception {
Controller에서 에러를 던져야 Controller Advice에서 잡으니.. throws Exception을 적어야 하지 않나요..? 안적으려면 try catch로 직접 에러처리를 하는 수 밖에는 없는 것 같은데.. 다른 방도가 있나요?

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/controller/RoundGameInterfaceImpl.java
> +    // 확률 랜덤값을 클라이언트로 부터 입력 받음
javadoc이 api 문서화와 주석 두가지 기능을 제공하는 api 이군요. 공부해 보고 조금 적용해 보았습니다. 감사합니다.

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +@ToString
데이터를 클래스에 담아서 외부로 return 할 때, tostring override를 하지 않으니 참조 주소 값만 보이더라구요.. 그래서 tostring override를 했습니다. 인터넷 서치를 해 보니, 서로가 서로를 순환 참조를 할때 stack overflow가 발생할 수 있다는 얘기가 있던데.. 위험성이라고 말씀하신다면 다음과 같은 상황 맞나요?

2023-01-10 15:28 UTC, yonggyujeong commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +public class HitterGameResultList {
넵.. 일급 컬렉션으로 만들어서 더이상 List 구조가 아닌데 List를 적는 것이 이상하네요.. 감사합니다. 수정했습니다.

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +    }
일급 컬렉션을 만들어 놓고 내부 객체를 반환했네요.. 해당 함수는 해당 클래스 반환 용도는 아니고, 리스트를 반환해서 조회용으로 썼는데, get(Integer index)로 수정해서 직접 안의 내용을 조회하면 되겠네요 감사합니다.

2023-01-10 15:28 UTC, prebird commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/service/BaseService.java
> +    }
네.. 생각해 보니, Base로직안에 득점 로직이 있는 것이 구조적으로도 어울리지 않네요.. 득점 로직을 roundService로 이동시켰습니다. 감사합니다.

2023-01-10 16:54 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/controller/RoundGameController.java
> +    public String hitting() throws Exception {
왜 이렇게 했나 코드를 보니 Exception 을 그대로 사용해서였군요.
Checked/Unchecked Exception 에 대해 학습해주세요.

2023-01-10 17:01 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/roundGame/domain/HitterGameResultList.java
> +@ToString
네. 그리고 ToString 으로 인해 표현이 제한되는 단점도 있습니다.

```java
@ToString
class AAADto {
    private final int a;
    private final int b;
    private final int c;
}
```

예를 들면 위의 클래스에서 ToString 을 활용하면 항상 a, b, c 가 노출될 것입니다.
하지만 위 dto 를 사용하는 A controller 에서는 a, b 만 보여야 되고, B controller 에서는 b, c 만 보여야 된다면 ToString 은 모호한 메서드가 됩니다.

개인적으로는 사용하지 않는 메서드입니다.

2023-01-10 17:12 UTC, Hyune-c approved these changes
> 리뷰 감사드립니다. 궁금한 점이 하나 있는데, roundGame의 구조가 만들면서 배우는 클린아키텍쳐를 읽으면서 해당 내용을 조금 반영을 한 것인데.. 혹시 구조가 조금 어색한가요? 현업의 관점에서는 의견이 어떠하신지 궁금합니다

조금 어색한 점이 있지만 전체적으로 좋은 시도의 코드라고 생각합니다.
- 애그리거트를 조금 더 묶을 수 있고, RoundGameService 를 조금 더 분리할 수 있을 것 같습니다.

현업이라는 것을 전제로 하면, 사실 이런 구조화보다는 팀 내부의 규칙이 중요합니다.
- 레이어간 사용하는 dto 의 prefix, suffix 정의
- service 레이어간의 순환 참조를 어떻게 해결할 것인가?
    - facade 레이어 도입, 레이어드 아키텍처 활용

---

긴 교육간 수고하셨습니다. 
혹시 또 듣게 되신다면 그 동안 쌓은 인사이트를 가지고 다시 처음부터 만들면, 또 다른 학습이 되실 것이라고 생각합니다.

감사합니다.

2023-01-11 03:29 UTC, yonggyujeong commented
감사합니다! 고생많으셨습니다!!

2023-01-11 03:29 UTC, merged