[일반 야구 1] 동일한 확률을 가지는 기능 구현
Programmers-Hyune-c/cosmic-baseball-init pull request #18
Opened 2023-02-02 11:21 UTC by kwYoohae

### 구현 목록
- Radom하게 동일한 확률로 strike, ball, hit를 생성하는 것을 테스트가 용이하도록 구조를 변경하였습니다. 

### 질문 하기
- 올려주신 백기선님의 유튜브 영상을 보았는데 이렇게 작은 단위로 PR을 올려도 되는지 궁금합니다. 
- 테스트 케이스를 통해서 동일확률이 어떻게 나오게 구성을 해야하는지에 대한 고민이 컸습니다. 이런방식대로 하는것이 맞는지 궁금합니다.

### 테스트 케이스 
<img width="602" alt="image" src="https://user-images.githubusercontent.com/74089271/216310392-292bd6cf-e302-42f4-8b9b-89cbca8d2729.png">

읽어주셔서 감사합니다 :)

2023-02-02 11:52 UTC, Hyune-c requested changes
> 올려주신 백기선님의 유튜브 영상을 보았는데 이렇게 작은 단위로 PR을 올려도 되는지 궁금합니다.

네. 하나의 lv 를 완성하기 위해 여러 번의 pr 을 올리셔도 무방합니다.

> 테스트 케이스를 통해서 동일확률이 어떻게 나오게 구성을 해야하는지에 대한 고민이 컸습니다. 이런방식대로 하는것이 맞는지 궁금합니다.

먼저 개발에 있어 맞고 틀림은 없습니다. 더 효율적인, 더 많은 케이스를 고려한 방법이 존재합니다.
어감의 차이 때문에 더 효율적인, 더 많은 케이스를 고려한 방법이 좋다고 보일 수 있지만, 반대로 말하면 불필요한 고민일 수 있습니다.

따라서 지금 구현하신 `랜덤 생성 로직을 덮어쓰는` 방법도 괜찮습니다.
하지만 테스트 클래스에서 사용한 `createRandom()` 이라는 메서드는 읽는 사람으로 하여금 랜덤 값이 나올 것 같아 보이는 네이밍입니다.
조금 더 고민할 키워드를 전달 드립니다.

- 전략 패턴, mock/stub

---

remote branch 에서 불필요한 테스트 코드를 삭제하고, 테스트 구현 없이는 에러가 나는 로직을 추가했습니다.
conflict 수정을 요청 드립니다.

2023-02-02 14:19 UTC, Hyune-c requested changes

2023-02-02 14:19 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomStrategy.java
> +  int getRandomNumber();
```java
randomStrategy.getRandomNumber()
```

- 무작위 숫자가 담긴 바구니에서 무작위 숫자를 뽑는다.
- 무작위 숫자가 담긴 바구니에서 숫자를 뽑는다.
- 숫자가 담긴 바구니에서 무작위 숫자를 뽑는다.

어떤 것이 낫다고 느껴지시나요.
그리고 전략에서 얻고자 하는 주체가 `랜덤` 인가요 `숫자` 인가요?

2023-02-02 14:19 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +}
eof 를 지켜주세요.

2023-02-02 14:19 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomBattingGenerator.java
> +  private static final int MAX_BATTING_NUMBER = 3;
`nit` Batting 의 가지 수 변경에 유연하지 못합니다.

2023-02-02 14:19 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/EqualRandom.java
> +public class EqualRandom implements RandomStrategy{
이 클래스가 사용되는 곳이 있나요?

2023-02-02 14:19 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/Batting.java
> +  STRIKE(0), BALL(1), HIT(2);
`nit` enum 변수와 value 를 맞추었기에 ordinal 을 그대로 사용하는 것보다는 낫습니다만 여전히 코드 스멜은 느껴집니다.

2023-02-02 14:19 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomBattingGenerator.java
> +    return Batting.of(random.getRandomNumber() % MAX_BATTING_NUMBER);
```java
public static Batting of(Integer value)
```

무엇을 보고 value 에 `랜덤 숫자를 MAX_BATTING_NUMBER 만큼 나눈 나머지` 를 넣어야 된다는 것을 알 수 있었나요?

2023-02-02 14:25 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomStrategy.java
> +  int getRandomNumber();
너무 `Random`만 생각하다보니 저런 메서드 이름이 나왔네요 
친절한 설명 너무 감사드립니다 :)

2023-02-03 02:47 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomBattingGenerator.java
> +  private static final int MAX_BATTING_NUMBER = 3;
Batting의 가짓수에 대해서 유연하게 작용하려고, 상수를 도입했었는데 
그것보다는 Batting의 크기를 받는게 더 유연하다고 판단해서 변경하였습니다!!!

리뷰 감사드립니다 :)

2023-02-03 02:48 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/EqualRandom.java
> +public class EqualRandom implements RandomStrategy{
<img width="721" alt="image" src="https://user-images.githubusercontent.com/74089271/216500569-e5f7e824-b9c7-4b57-b12c-a1ff0cb7dc5b.png">
다음처럼 `BattingGenerator`를 구현하는 클래스에서 `@Component`를 이용하여서 빈 주입을 받아서 사용을 하고 있습니다!!

2023-02-03 02:50 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/Batting.java
> +  STRIKE(0), BALL(1), HIT(2);
`ordinal` 을 사용하면, 중간에 변수가 추가되었을때, 변경이 될 수 있다는 점에서 변경하였습니다

`enum`에 대한 이해가 부족한것 같은데 혹시 어떠한 코드 스멜이 나타나는지 궁금합니다 :)

개인적인 생각으로는 의미있는 값이 아닌 ordinal과 value 같은 값을 쓰기 때문이라고 생각이 드는데 아직 식견이 넓지 못해서 
어떠한 코드 스멜이 나는지 확실하게 모르겠습니다 혹시 알려주실 수 있을까요?

2023-02-03 02:51 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomBattingGenerator.java
> +    return Batting.of(random.getRandomNumber() % MAX_BATTING_NUMBER);
확인해보고, `Exception` 을 추가하는 방식으로 변경을 해보았습니다. 그러면 사용자들도, 값을 넣었을때 오류 메세지를 보고 판단할 수 있을 거라고 생각 했습니다 :)

2023-02-03 03:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/EqualRandom.java
> +public class EqualRandom implements RandomStrategy{
![image](https://user-images.githubusercontent.com/55722186/216508296-cff9235b-bc06-4b6b-860f-9866ea3862a2.png)

구현체가 한개이기에 자동으로 매칭되는 것을 활용하신 거군요. 
이런 경우 패키지 구조를 맞추거나, 전략 변경을 대비해 팩토리 패턴을 활용하는 것을 추천합니다.

2023-02-03 03:51 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/Batting.java
> +  STRIKE(0), BALL(1), HIT(2);
이건 다음 레벨을 진행하면 체감할 수 있을 거라고 생각하여 패스하겠습니다.

2023-02-03 03:52 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/EqualRandom.java
> +public class EqualRandom implements RandomStrategy{
감사합니다 :) 확인해보고 공부한 뒤 변경하도록하겠습니다

2023-02-03 03:57 UTC, Hyune-c approved these changes

2023-02-03 03:57 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/BattingTest.java
> +  }
좋은 단위 테스트 입니다. 👍
`Assertions` 은 static import 를 추천합니다.

2023-02-03 03:57 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/exception/ExceptionMessage.java
> +  public static final String VALUE_MUST_BE_SMALLER_THAN_BATTING_SIZE = "Batting으로 변환하려는 숫자 값은 반드시 Batting의 크기보다 작거나 0보다 커야합니다.";
```java
STRIKE(0), BALL(1), HIT(7);

public static Batting of(Integer value) {
  return Arrays.stream(Batting.values())
      .filter(e -> e.value.equals(value))
      .findFirst()
      .orElseThrow(() -> new IllegalArgumentException(ExceptionMessage.VALUE_MUST_BE_SMALLER_THAN_BATTING_SIZE));
}
```

이 코드에서 `Batting.of(5)` 는 어떤 결과가 발생하나요?

2023-02-03 03:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/RandomBattingGenerator.java
> +    return Batting.of(random.getRandomNumber() % MAX_BATTING_NUMBER);
https://github.com/Programmers-Hyune-c/cosmic-baseball-init/pull/18#discussion_r1095331226

이쪽의 리뷰에서 진행합니다.

2023-02-03 06:16 UTC, kwYoohae commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/exception/ExceptionMessage.java
> +  public static final String VALUE_MUST_BE_SMALLER_THAN_BATTING_SIZE = "Batting으로 변환하려는 숫자 값은 반드시 Batting의 크기보다 작거나 0보다 커야합니다.";
같은 Exception이 발생하긴 하는데, Exception에 대한 네이밍에 대해서 올바르지 않은 것 같기도하고, 너무 많은 의미를 함축하는것 같아서 좀 더 고민을 해봐야할것 같습니다

예제까지 해서 리뷰 달아주셔서 감사합니다 :) 좀 더 이해가 빨라졌습니다

2023-02-03 09:17 UTC, Hyune-c approved these changes
### 커밋에 `@` 를 사용하면 엄한 사람이 링크 될 수 있습니다.

![image](https://user-images.githubusercontent.com/55722186/216560534-a56f4756-59bb-4dab-8ba0-6a6cddbed436.png)

### 이미 approve 된 pr 은 또 요청하실 필요 없이 진행하셔도 됩니다.

![image](https://user-images.githubusercontent.com/55722186/216561023-e4097f9d-3dc2-415b-be56-234fe4eba692.png)

2023-02-03 09:51 UTC, kwYoohae commented
확인했습니다 :) 다음 부터는 커밋에 `#` 또는 `@` 를 조심하도록 하겠습니다!!!

2023-02-05 06:38 UTC, merged