1차 pr review 에 대한 수정과 브랜치 dev 변경
Programmers-Hyune-c/cosmic-baseball-init pull request #30
Opened 2023-02-19 10:06 UTC by yuni02

REFACTOR: 
- 불필요한주석 코드 제거 
- else 삭제 
- 변수명 수정
- overload 한 메서드 하나로 통합 Getter 사용하여 중복 메서드 제거

2023-02-19 11:14 UTC, Hyune-c requested changes
전체적으로 setter 의 활용이 너무 잦습니다.
불변성과 객체에 메세지를 전달한다에 대해 좀 더 고민해주세요.

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/exception/ExceptionMessage.java
> +        public static final String CANNOT_PROCEED_ATBAT = "현재 타석이 진행중이라, 새로운 게임이 불가능 합니다.";
직역하면 `배팅을 진행할 수 없습니다.` 입니다. 새로운 게임과는 의도가 전혀 다릅니다.

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/Batting.java
>      }
모두 하드 코딩되어 있네요.
하지만 다음 기능을 하면서 개선될 것으로 기대합니다.

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    private final Map<String, String> player = new HashMap<String, String>();
단수형, 복수형 사용에 일관성을 가져주세요.

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    private static PlateAppearances pa;
이 객체의 의도를 잘 모르겠습니다.
PlateAppearances 안에 왜 또 PlateAppearances 가 있는건가요?

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
`예상 가능하고 명백하게 구분되는 상태` 라면 String 보다 좋은 방법이 있지 않을까요?

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
- 변수명을 고민해주세요. 너무 모호합니다.
- setter 의 사용을 다시 고민해주세요.

2023-02-19 11:14 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
```suggestion
    public void setTotalOutCount() {
        this.totalOut++;
    }
```

이런 오타는 이력서의 맞춤법이 틀림과 같습니다.
필히 신경 써주세요.

2023-02-19 11:37 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/exception/ExceptionMessage.java
> +        public static final String CANNOT_PROCEED_ATBAT = "현재 타석이 진행중이라, 새로운 게임이 불가능 합니다.";
넵 직역이 잘못된것 같습니다. 변수명 지을때 조금 더 신중을 기하겠습니다.

2023-02-19 11:41 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
힌트를 주실 수 있을까요? 저번부터 감이 잘 잡 안혀서요

2023-02-19 11:42 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
넵 감사합니다. 지적감사드립니다^^

2023-02-19 11:51 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    private static PlateAppearances pa;
PlateAppearance를 싱글톤으로 하다보니까 변하지 않는 변수가 필요해서 만들었습니다.

2023-02-19 11:54 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    private final Map<String, String> player = new HashMap<String, String>();
넵

2023-02-19 12:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
> key 가 플레이어 이름이고, value 가 게임의 진행 상태인 것을 볼 때, 
player map 에서 관리되는 것 은 `각 플레이어별 게임 진행 상태` 인 것으로 추정됩니다.

- map 의 변수 명이 player 인 것은 적절하지 않습니다. value 가 진행 상태라는 것을 추측할 수 없기 때문입니다.
- 게임의 진행 상태가 명시적으로 3개라면 enum 을 활용할 수 있습니다.

2023-02-19 12:02 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    private static PlateAppearances pa;
- `@Component` 는 Spring Bean 을 만들어 줍니다.
- 정작 pa 가 사용되는 곳은 `getInstance()` 뿐이고, 그 메서드는 테스트 코드에서만 사용되고 있습니다.

위 두가지를 키워드로 다시 생각해봐주세요.

2023-02-19 23:17 UTC, yuni02 reviewed
코멘트에 대한 코드 수정 후 리뷰요청드립니다.

2023-02-20 02:33 UTC, Hyune-c requested changes
사용하지 않는 코드는 주석이 아니라 지워주세요.

2023-02-20 02:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
중첩 if 문을 해결해주세요.
early return 만 하여도 많이 해결될 것으로 보입니다.

2023-02-20 02:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
이 메서드는 newGame 을 하는 init 의 역할만 하면 될 것 같은데, 현재 상태에 대한 판단까지 같이 하고 있네요.
하나의 메서드가 너무 많은 일을 하고 있는 것이 아닌지 고민해주세요.

2023-02-20 02:33 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
>      }
```suggestion
    public static boolean compareThreeValues(int n1, int n2, int n3) {
        boolean equation1 = 0 <= Math.abs(n2 - n1) / 100 && Math.abs(n2 - n1) / 100 < 5;
        boolean equation2 = 0 <= Math.abs(n3 - n2) / 100 && Math.abs(n3 - n2) / 100 < 5;
        return equation1 && equation2;
    }
```

`nit`

2023-02-20 02:33 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertEquals(result, true);
```suggestion
        assertTrue(result);
```
`nit` 저는 일관성을 위해 assertThat 의 활용을 추천합니다.

2023-02-20 02:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +            battings.clear();
포볼이 되면 배팅을 초기화하는 것까지 같이 하고 있군요.
나쁘지 않은 구현이지만 하나의 메서드가 해야되는 일이 너무 많은 것이 아닌가 고민해주세요.

2023-02-20 03:16 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
네 기능을 나눠보겠습니다.

2023-02-20 03:18 UTC, yuni02 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
>      }
훨씬 간결해보이네요

2023-02-20 03:32 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +    }
넵

2023-02-20 05:22 UTC, Hyune-c requested changes

2023-02-20 05:22 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(pa.newGame()).isEqualTo(ExceptionMessage.NEW_GAME_START);
game 의 결과가 exception 이 아니라 message 라는건 매우 이상합니다.

2023-02-20 05:22 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
> +        if (result().equals(BattingResult.FOUR_BALL) || result().equals(BattingResult.OUT)) return true;
- if 이후의 공백 처리가 일관적이지 않습니다.
- == 이후 숫자가 나오기 전 공백이 없습니다.
- if 문의 중괄호가 없습니다.
- 조건문이 2개 이상인 if 문이 1줄로 표현되고 있습니다.

https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style

기초적인 컨벤션이 많이 어긋나고 있습니다.
sonarlint 및 컨벤션 포매팅을 활용해주세요.

---

실무라면 리뷰 거부를 하고, 코테 자료라면 바로 탈락을 주는 내용입니다.

2023-02-20 06:12 UTC, yuni02 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(pa.newGame()).isEqualTo(ExceptionMessage.NEW_GAME_START);
newGame 의 함수명을 바꾸는게 낫다고 제안해주시는 걸까요?

2023-02-20 06:32 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(pa.newGame()).isEqualTo(ExceptionMessage.NEW_GAME_START);
아니오. 예외 처리는 String 응답이 아니라 예외 객체를 throw 해야된다는 것을 말하는 것입니다.

- exception handling 에 대해 공부해주세요.

2023-02-20 11:28 UTC, Hyune-c approved these changes
수정한 부분의 띄어쓰기 컨벤션이 지켜지지 않고 있습니다.
linter 등을 활용하여 컨벤션을 지켜주세요.

2023-02-20 11:28 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
>      }
이전보다 발전되었네요. 👍
하지만 여전히 지금의 코드는 적절하지 않습니다.
`체크드 익셉션 vs 언체크드 익셉션` 에 대해 학습해주세요.

---

하지만 이번 pr 이 너무 길어지고 있고, 충분한 피드백이 되었다고 생각하여 approve 합니다.

2023-02-20 12:06 UTC, yuni02 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/baseball/model/PlateAppearances.java
>      }
네 체크드 익셉션 vs 언체크드 익셉션에 대해서 학습해보겠습니다.

2023-02-20 12:08 UTC, merged