Level1 구현
Programmers-Hyune-c/cosmic-baseball-init pull request #35
Opened 2023-03-02 15:06 UTC by choizz156

Level 1을 구현해보았는데, 타격 결과가 같은 확률로 나오게 하는 테스트 코드는 제대로 작성하지 못 한것 같습니다.
리뷰 부탁드리겠습니다!

2023-03-02 15:18 UTC, Hyune-c requested changes
- 일반 야구 구현인데 테스트 코드는 `우주 야구 CosmicBaseballLv1Test.java` 입니다.
![image](https://user-images.githubusercontent.com/55722186/222470292-55acbd1b-0075-4e14-912c-7cf735466ba4.png)

- 테스트 성공한 이력을 캡쳐로 올려주세요.

2023-03-02 15:31 UTC, choizz156 reviewed
![image](https://user-images.githubusercontent.com/106965005/222473193-2ce14f4e-0266-40c0-b02f-01b404c99307.png)
제가 클래스 네임을 확인을 못 했습니다! 주의하겠습니다!

2023-03-02 16:03 UTC, Hyune-c requested changes
![image](https://user-images.githubusercontent.com/55722186/222483105-592bbe7a-6633-4a67-8b21-726bb2583a53.png)

지금의 구현에는 로직만 있을 뿐 API 서버의 역할이 없습니다.
프론트엔드 개발자가 호출할 수 있는 형태를 만들어주세요.

2023-03-02 16:03 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(result).isIn(STRIKE, BALL, HIT);
- 이 테스트 코드는 t2 에 더 가까운 것 같습니다.
- 확률에 대한 테스트는 어떻게 진행하면 좋을까요?

2023-03-02 22:02 UTC, choizz156 reviewed
백엔드 api 생성했습니다! 

타격 결과에 대한 테스트 코드는 조금 더 고민해 보겠습니다.

2023-03-02 23:13 UTC, choizz156 reviewed
정확한 테스트는 아닌 것 같지만 테스트 구현 논리를 대략적으로 말씀드리겠습니다.

>전체 가정은 random.nextInt(3)에서 0 , 1, 2가 나올 확률은 같다고 생각했습니다.
 그래서 십 만번 정도 수행을 하면, 0, 1, 2, 모두 33,300번이 나올 거라고 가정했습니다.
  
  ---
1. 배팅을 했을 때, 결과 값을 랜덤으로 가지고 온다.
2. 결과 값은 enum 값이므로 ordinal() 값이 있다.
3. random.nextInt(3) 에서 나온 랜덤 값과 타격 결과의 ordinal이 같다면, count를 늘린다. ( getBattingResultCount 메서드에서 수행)
4. 이 테스트를 10번 정도 수행한다.

- 결과: 10번 모두 33,300의 1% 내외의 오차로 count 값이 나왔다. 따라서,  무한대로 수행을 한다고 가정하면, 타격 결과는 동일하다고 볼 수 있다.

---
좀 무식한 방법인 것 같은데 리뷰 부탁드립니다!

![image](https://user-images.githubusercontent.com/106965005/222583874-687aaf70-839e-4d3c-8fc4-75618aae812e.png)

2023-03-02 23:15 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +	@Test
정확한 테스트는 아닌 것 같지만 테스트 구현 논리를 대략적으로 말씀드리겠습니다.

>전체 가정은 random.nextInt(3)에서 0 , 1, 2가 나올 확률은 같다고 생각했습니다.
 그래서 십 만번 정도 수행을 하면, 0, 1, 2, 모두 33,300번이 나올 거라고 가정했습니다.
  
  ---
1. 배팅을 했을 때, 결과 값을 랜덤으로 가지고 온다.
2. 결과 값은 enum 값이므로 ordinal() 값이 있다.
3. random.nextInt(3) 에서 나온 랜덤 값과 타격 결과의 ordinal이 같다면, count를 늘린다. ( getBattingResultCount 메서드에서 수행)
4. 이 테스트를 10번 정도 수행한다.

- 결과: 10번 모두 33,300의 1% 내외의 오차로 count 값이 나왔다. 따라서,  무한대로 수행을 한다고 가정하면, 타격 결과는 동일하다고 볼 수 있다.

---
좀 무식한 방법인 것 같은데 리뷰 부탁드립니다!

2023-03-03 02:39 UTC, Hyune-c requested changes

2023-03-03 02:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballContoroller.java
> +	}
- `@RestController 의 역할` `ResponseEntity 의 사용`
- 반환 값에 ResponseEntity 만 존재

위 항목에 대한 생각을 말해주세요.

2023-03-03 02:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Batter.java
> +	private Random random = new Random();
랜덤 객체가 매번 생성되어야 할까요?

2023-03-03 02:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Batter.java
> +	}
nullsafe 하면서도 간결한 코드로 개선 가능할 것 같습니다.
hint. switch 매개변수 inline

2023-03-03 02:39 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +	@Test
꽤 괜찮은 접근 방법입니다.
이번 레벨에서는 이 정도로 넘어가도 될 것 같습니다.

2023-03-03 02:39 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +		Assertions.assertThat(count).isCloseTo(33_300, Percentage.withPercentage(1));
`nit` Assertions 은 static import 를 추천합니다.

2023-03-03 02:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/ComicBaseballService.java
> +		Batter batter = new Batter();
`nit` 객체 생성에 대한 고민을 해주세요
이번 레벨을 넘어가는 것이기에 nit 으로 코멘트 합니다.

2023-03-03 07:00 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballContoroller.java
> +	}
- @RestController 의 역할 ResponseEntity 의 사용
     - @RestController는 @ResponseBody와 @Controller가 합쳐진 것이고, 프론트엔드에서 요청이 왔을 때, response에 리턴하는 데이터를 보낼 수 있기 때문에 사용했습니다. 
     - ResponseEntity는 상태 코드를 관리할 수 있기 때문에 사용했습니다. 그리고 타격 결과를 response에 같이 담아서 보냈습니다. 
    
- 반환 값에 ResponseEntity 만 존재
      -  상태 코드를 지정할 수 있다는 점에서 ResponseEntity만 사용해도 괜찮을 것 같다는 생각이 듭니다.

2023-03-03 07:38 UTC, choizz156 reviewed
Random 클래스를 싱글톤 패턴으로 객체가 하나만 생성되게 했습니다.

2023-03-03 07:40 UTC, choizz156 reviewed
switch 문을 리팩토링 해보았습니다

2023-03-03 07:42 UTC, choizz156 reviewed
Batter 객체를 DI하여 new 생성을 하지 않게 했습니다.

2023-03-03 07:42 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Batter.java
>  	private BattingResult getResult() {
스위치문을 리팩토링 해보았습니다.

2023-03-03 07:50 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/util/NumberFactory.java
> +package com.hyunec.cosmicbaseballinit.util;
Factory 클래스를 싱글톤 패턴으로 만들어 Random 객체를 하나만 생성하게 했습니다.

2023-03-03 08:46 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +	}
왜 `NumberFactory` 를 사용하지 않았나요?

2023-03-03 08:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/util/NumberFactory.java
> +}
spring 에서의 싱글턴이라면 조금 더 좋은 방법이 있을 것 같습니다.

2023-03-03 08:46 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +	}
이 메서드는 count 를 오염시키는 부수 효과를 가지고 있습니다.

2023-03-03 08:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Batter.java
> +public class Batter {
import 를 정리하고, 개행을 하는 것도 컨벤센의 일종입니다.
그리고 컨벤션을 지키지 못함은 이력서의 오타, 맞춤법 틀림과 같습니다.

2023-03-03 08:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/ComicBaseballService.java
> +	private final Batter batter;
`nit` 네이밍을 고민해주세요. 
- batter 라는 네이밍은 bean 보다는 개인화된 객체로 읽힙니다.

2023-03-03 08:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballContoroller.java
> +	}
`@` 멘션에 주의해주세요.
![image](https://user-images.githubusercontent.com/55722186/222672183-8297a292-e1f9-47e1-a81f-3f3969472d21.png)

---

> `@RestController` 의 역할 ResponseEntity 의 사용
> `@RestController`는 `@responsebody`와 `@controller`가 합쳐진 것이고, 프론트엔드에서 요청이 왔을 때, response에 리턴하는 데이터를 보낼 수 있기 때문에 사용했습니다.
> ResponseEntity는 상태 코드를 관리할 수 있기 때문에 사용했습니다. 그리고 타격 결과를 response에 같이 담아서 보냈습니다.

- ResponseEntity 를 사용하지 않으면 상태 코드를 변경할 수 없나요?
- Controller, RestController 의 유스 케이스를 공부해주세요.

> 반환 값에 ResponseEntity 만 존재
> - 상태 코드를 지정할 수 있다는 점에서 ResponseEntity만 사용해도 괜찮을 것 같다는 생각이 듭니다.

```java
@GetMapping("/batting")
public ResponseEntity hit() { ... }
```

- 프론트엔드 개발자는 이 api 의 반환 값이 무엇인지 알 수 있을까요?
- 심지어 백엔드 개발자라고 하더라도 시그니처를 보고 알 수 있을까요?

2023-03-03 08:48 UTC, Hyune-c approved these changes
비교적 작은 기능임에도 불구하고 리뷰가 길어지고 있네요.
기능상 큰 문제는 없으니 이번 PR 은 지금의 코멘트까지만 진행 합니다.

2023-03-03 09:32 UTC, merged