Level1 우주야구 double_strike 까지만
Programmers-Hyune-c/cosmic-baseball-init pull request #36
Opened 2023-03-03 15:37 UTC by choizz156

2023-03-03 17:03 UTC, choizz156 reviewed
리뷰 부탁드립니다!

2023-03-03 17:03 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BallCountService.java
> +}
볼 카운트를 변화시키는 클래스를 작성했습니다.

2023-03-03 17:03 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/service/ComicBaseballService.java
> +    }
ComicBaseballService가 battingService, ballCountService에게 각각 할 일을 위임하는데 
굳이 ComicBaseballService가 필요한지는 잘 모르겠습니다. 없어도 될 것 같습니다..

2023-03-03 17:03 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/dto/ResponseDto.java
> +}
볼 카운트를 리턴하기 위한 dto 클래스를 만들었습니다.

2023-03-03 17:03 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +        return ResponseEntity.ok().body(responseDto);
dto 객체를 생성해,  dto를 데이터로 내려보내게 했습니다.

2023-03-03 17:03 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/util/RandomFactory.java
> +}
테스트 코드에서만 사용할 Random 객체를 싱글턴으로 구성했습니다.

2023-03-03 17:03 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/ResultCount.java
> +}
확률을 구하는 테스트 코드에 사용되는 로직을 상위 클래스로 하고, 이 로직을 사용하는 클래스가 상속하게 하여 코드 중복을 없앴습니다.

2023-03-03 17:03 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
> +
`@BeforeEach`를 이용해서 테스트가 수행되기 전에 새로운 hashmap 객체를 생성하게 했습니다. 

이 방법 이외에 효율적인 방법이 있을까요?

2023-03-03 17:03 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
> +
우주야구 level1에 대한 테스트 코드입니다.

![image](https://user-images.githubusercontent.com/106965005/222774085-3487fa49-81f3-4d34-8850-1d6786a1d212.png)

@DisplayName("ball이 나올 시 스트라이크 카운트를 한 개 증가시킵니다.")
오타 나중에 수정하겠습니다.

2023-03-03 18:26 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BallCountService.java
> +}
전략 패턴을 사용하여 다시 구현하였습니다. 후에 다시 리뷰요청하겠습니다!

2023-03-03 23:47 UTC, Hyune-c requested changes
우주 야구 lv1 이라고 올리셨지만, 일반 야구 lv1 의 리팩토링이 섞여 있습니다.
일반 야구의 커밋부터 pr 을 올려주세요.

리뷰는 진행하지 않았습니다.
저번 피드백에 대한 추가 의견을 드립니다.

---

> RestController 와 ResponseEntity 에 대해
- https://stackoverflow.com/questions/26549379/when-use-responseentityt-and-restcontroller-for-spring-restful-applications
- `To complete the answer from Sotorios Delimanolis.` 로 시작하는 답변이 제 생각과 가깝습니다.
- RestController 어노테이션은 ResponseEntity 를 생략할 수 있음을 내포하고 있습니다.
- 유지보수 관점에서는 불필요한 코드를 늘려 관심사가 흐려집니다.
- 상급자의 입장에서는 어노테이션의 활용에 대한 고민이 부족한 것이라고 생각되게 만듭니다.

> 테스트는 느려도 되는가 
> - 느리면 조금 답답합니다.. 느리지 않은 것이 좋은 것 같습니다.
- 테스트에 대한 이야기는 너무 딥하게 하면 어려울 것 같네요.
- 3주차에 예정된 내용이 있으니 그때 추가 하겠습니다.

> 행위가 있는 객체를 런타임에 생성해도 되는가 
> - 생성해도 상관은 없을 것 같지만 스프링에 빈으로 등록해 사용하듯이 사용하는 것이 효율적일 것 같습니다.
- 웹 애플리케이션의 관점에서 모든 요청은 간결함을 권장합니다.
- 따라서 최대한 부수 효과가 없는 싱글톤 객체를 미리 생성해서 사용함을 권장합니다.
- 다시 생각해보니 테스트에 대한 질문이었는데 조금 많이 나간 키워드 같네요.

> 픽스쳐란 무엇인가 
> -  픽스쳐에 대해 검색을 해보니, beforeEach나 beforeAll은 테스트 뿐만 아니라 다른 코드에도 영향을 줄 수 있는 것 같습니다. 
> - https://jojoldu.tistory.com/611
- 픽스쳐에 대한 질문을 드렸는데 beforeEach나 beforeAll 의 영향도를 조사해오신 것 같네요.
- 픽스쳐란 무엇이고 왜 필요한가 학습해주세요.  
- `test code를 구현할 때도 new 생성자를 이용한 객체 생성 이나 static 키워드 사용 같은 것을 신경써야 할까요??` 질문에 가장 근접한 키워드 입니다.

---

테스트에 대한 내용은 지금 다루기에는 꽤 어려운 주제 같습니다.
이번 피드백까지만 진행하고, 3주차에 예정된 내용이 있으니 그때 추가 하겠습니다.

2023-03-04 07:47 UTC, Hyune-c commented
일반 야구가 모두 완료된 후 다시 올려주세요. or 이슈를 재 오픈 하시면 됩니다.

2023-03-04 07:47 UTC, closed without merging