Level1 일반 야구 (2)
Programmers-Hyune-c/cosmic-baseball-init pull request #37
Opened 2023-03-04 07:01 UTC by choizz156

2023-03-04 07:33 UTC, choizz156 reviewed
피드백을 반영하여 리팩토링해 보았습니다!

2023-03-04 07:33 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
>  }
Enum에 index를 추가했습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/util/UtilConfig.java
> +}
Random 클래스를 빈으로 등록해 사용했습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingService.java
> +	private BattingResult getResult() {
클래스명을 변경하고 Random 클래스를 di하여 사용했습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/dto/ResponseDto.java
> +}
dto를 생성했습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>  }
ResponsEntity를 제거하고 dto를 리턴하게 했습니다. 
상태코드는 @ResponseStatus로 고정시켰습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/RandomFactory.java
> +}
테스트 코드에서만 사용될 랜덤 객체를 생성할 클래스를 싱글턴으로 만들었습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    private Random random = RandomFactory.getInstance();
RandomFactory에서  객체를 생성하고 테스트에서 사용했습니다.

2023-03-04 07:33 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    }
프로덕션과 똑같은 로직을 테스트 클래스 내에 생성하여 사용했습니다. 프로덕션 코드를 가져와 사용하지 않았습니다.

2023-03-04 07:46 UTC, Hyune-c requested changes
개발 의도를 설명하기 위해 pr 리뷰에서 코드 밑에 설명을 다는 것은 좋은 습관입니다.
하지만 코드만으로도 명백히 보이는 내용에 대해서는 달지 않으셔도 됩니다.

예를 들어 `dto를 생성했습니다.` 와 같은 코멘트는 의미가 적습니다.

- 코드만으로는 설명이 힘든 개발 의도 설명이 필요하거나
- 질문이 있는 경우 남겨주세요.

2023-03-04 07:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +	@ResponseStatus(HttpStatus.OK)
200 ok 는 생략할 수 있습니다.

2023-03-04 07:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +	public ResponseDto hit() {
api 는 batting 인데 메서드 명은 hit 입니다.
일관성을 지켜주세요.

2023-03-04 07:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dto/ResponseDto.java
> +    }
`nit` lombok 을 활용할 수 있을 것 같습니다.

2023-03-04 07:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
>  }
값을 지정했기에 ordinal 과는 다르다고 생각할 수 있겠지만, 네이밍이 index 라면 ordinal 과 다름 없어 보입니다.
그리고 index 는 테스트 코드에서만 쓰이는거 같은데 의도한 것인가요?

2023-03-04 07:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dto/ResponseDto.java
> +}
`표준 응답 객체` 개념을 가져오셨네요.
api 가 더 늘어난 후 피드백 하겠습니다.

2023-03-04 07:46 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    private Random random = new Random();
`RandomFactory` 를 테스트에서만 쓰기위해서 만들었다고 주석을 달아놓았지만 여전히 새로 생성하고 있습니다.

2023-03-04 07:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingService.java
> +	private final Random random;
보통 random 이라는 클래스는 java random 을 먼저 떠올리게 됩니다.

- hint. 전략 패턴, 조금은 결이 다르지만 `예약어` 개념에 대해 학습해주세요.

2023-03-04 07:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingService.java
> +	private BattingResult getResult() {
리뷰를 받기 전부터 outdated 된 코멘트가 있네요.
신경써주세요.

2023-03-04 07:51 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
>  }
넵 의도한것이긴합니다. 눈에 직관적으로 보이게 하려고 사용했습니다

2023-03-04 07:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
>  }
개선의 여지는 있지만 지금은 넘어가겠습니다. 
hint. ordinal

2023-03-04 08:32 UTC, choizz156 reviewed
인터페이스를 사용해서 random 클래스를 다시 빈으로 등록했습니다.
리뷰 부탁드립니다.

--> 제가 만든 방식이 random 객체가 싱글톤하지 않을 것 같습니다. 다시 한번 고민해보겠습니다.

2023-03-04 17:16 UTC, choizz156 reviewed
랜덤 숫자를 생성하는 객체를 빈으로 등록했습니다!
리뷰 부탁드리겠습니다!

2023-03-04 19:58 UTC, Hyune-c requested changes
기본기가 있으시고, 전체적인 흐름은 구현하고 계십니다.
하지만 디테일이 부족합니다. 특히 네이밍과 패키지 위치를 고민해주세요.

PR 리뷰 주기가 너무 빨라서 그렇다는 느낌이 들어서 `일반 야구 lv1` 이후에는 리뷰 주기를 조금 늦추는 것을 고려하겠습니다.
멘티님도 조금 여유를 가지고 다른 공부와 병행하면 좋을 것 같습니다.

2023-03-04 19:58 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +        BattingResult result = battingService.hit();
`nit` 
여전히 batting 과 hit 의 일관성이 맞지 않는 것 같습니다.
실무에서는 용어 정의가 매우 중요합니다.

2023-03-04 19:58 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/util/RandomGeneratorImpl.java
> +    }
- 네이밍은 `getRandomNumber()` 이지만 내부 로직에는 BattingResult.length 가 있습니다. 
    - 도메인 로직이 들어가 있는 것 같군요. 
    - util 은 더 작고 보편적으로 만들 것을 권장합니다.
- `RandomGenerator.getRandomNumber()`  
    - random 이라는 표현이 중복되는 것 같습니다.

2023-03-04 19:58 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/util/RandomGeneratorImpl.java
> +    private final Random random = new Random();
- 싱글톤 패턴이 상태를 가져도 되는가?
- 클래스 변수, 인스턴스 변수, 로컬 변수에 대해 학습해주세요.

2023-03-04 19:58 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    private Random random = RandomFactory.getInstance();
`nit` bean 으로 등록했다면 그냥 사용하면 되는데, SpringBootTest 를 사용하지 않기 위해 의도적으로 한 것인가요?

2023-03-05 04:20 UTC, Hyune-c approved these changes

2023-03-05 15:25 UTC, choizz156 reviewed
## 늦은 시간까지 리뷰를 해주셔서 정말 감사드립니다!!

random 객체를 빈으로 등록하고 RandomGeneratorImpl에 di해서 사용해보았습니다.


----

```
• 싱글톤 패턴이 상태를 가져도 되는가?

멀티 스레드 상황에서 여러 스레드들이 싱글톤 객체를 공유하게 됩니다.

여러 스레드에서 객체의 상태를 변화시키는 메서드를 사용 하면, 싱글톤 클래스의 상태를 변화시킬 수 있습니다.

따라서, 싱글톤 패턴에서는 필드를 가져서는 안됩니다. 이것은 스프링 빈으로 등록되는 클래스들도 마찬가지일 것 입니다.

```

궁금한 것이 생겨 질문드립니다.

1. 상태를 변경하는 메서드가 없다면 싱글톤 패턴에서 상태를 가져도 될까요?

```
private final Random random = new Random(); //이 코드는 클래스 내에 상태를 변경시킬 메서드가 없어서 빈 객체가 초기화된 후에 외부에서 변경될 일이 없을 것 같습니다.

```

1. Random 객체를 싱글톤화 하지 않고 클래스 변수로 만들어서 사용하는 방법은 좋지 못한 방법일까요?

2023-03-05 15:25 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    private Random random = RandomFactory.getInstance();
springboottest를 사용하면 스프링부트 로딩 시간이 있어서 약간 테스트가 느려지는 것 같아서 따로 만들었습니다.

2023-03-05 15:25 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/util/RandomGeneratorImpl.java
> +        return random.nextInt(bound);
>

2023-03-05 15:25 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/util/RandomGeneratorImpl.java
> +    private final Random random;
###

2023-03-05 16:05 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/util/RandomGeneratorImpl.java
> +    private final Random random;
> 상태를 변경하는 메서드가 없다면 싱글톤 패턴에서 상태를 가져도 될까요?

```java
private final Random random = new Random(); 
```

- 기능적으로 안될 것은 없습니다. 
- 위 변수의 종류와 JVM 메모리 상 어디에 올라가는지 생각해주세요.

> Random 객체를 싱글톤화 하지 않고 클래스 변수로 만들어서 사용하는 방법은 좋지 못한 방법일까요?

- 좋다고 생각합니다.
- 사실 지금의 코드에서 RandomGenerator 가 interface 로 까지 있어야되는지 와닿지 않습니다.

2023-03-06 01:54 UTC, choizz156 reviewed
random 객체를 클래스 변수로 할당하였습니다.
리뷰 부탁드립니다!
-----
```java
private final Random random = new Random(); 
```
위 변수의 종류와 JVM 메모리 상 어디에 올라가는지 생각해주세요.

- random 객체는 인스턴스 변수이고,  객체 생성 시 jvm 런타임 영역에서 힙 영역에 올라갑니다. 후에 사용되지 않는다면, gc에 의해 정리될것 같습니다. 그래서, 클래스 변수로 두고 사용하는 것이 좋을 것 같습니다.

2023-03-06 06:49 UTC, Hyune-c approved these changes

2023-03-06 06:49 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingService.java
> +}
```suggestion
@Service
public class BattingService {

    private static final Random RANDOM = new Random();

    public BattingResult batting() {
        return BattingResult.values()[RANDOM.nextInt(BattingResult.values().length)];
    }
}
```

`nit` 현재 요건을 위해서 아마 저라면 이렇게 할 것 같습니다.
향후 `BattingResult 를 생성해야 되는 전략이 변경된다면` strategy 로 분리할 듯 합니다.

2023-03-06 06:49 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    }
`nit` prod 코드에서 전략 교체가 불가능하기에 이 코드들은 큰 의미가 없어졌습니다.

2023-03-06 08:15 UTC, Hyune-c approved these changes
approved 된 pr 은 심각한 내용이 아니라면 재 요청하실 필요 없습니다.
자체적으로 수정하고 머지하셔도 됩니다.

2023-03-06 08:15 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +    private int getCount() {
`nit` prod 코드라면 좀 더 의도가 있어야 합니다. 무엇에 대한 count 인지 모르겠습니다.
하지만 test 코드이기에 넘어가도 됩니다.

2023-03-06 08:15 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +            BattingResult.values().length)];
`nit` 개행의 기준이 모호하네요. 

- 32번째 줄은 한줄로 사용함.
- (관례적임) 매개변수를 시작하는 괄호에서 개행을 한다면, 닫는 괄호에서도 개행을 추천합니다.

2023-03-06 08:15 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(getCount()).isCloseTo(33_300, Percentage.withPercentage(1));
Percentage 는 처음 본 api 네요. 👍

2023-03-06 08:15 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(result).isBetween(STRIKE, BALL);
```java
// as-is
public enum BattingResult {
    STRIKE, HIT, BALL;
}

// to-be
public enum BattingResult {
    STRIKE, BALL, HIT;
}

// to-be 2
public enum BattingResult {
    STRIKE, HIT2, BALL, HIT;
}
```

enum 이 변화되면 이 코드는 어떻게 되나요?

2023-03-06 10:11 UTC, merged