우주 야구 level1 (double strike)
Programmers-Hyune-c/cosmic-baseball-init pull request #45
Opened 2023-03-07 11:35 UTC by choizz156

우주 야구 level1 double stirke 까지만 구현해 보았습니다.

2023-03-07 11:59 UTC, choizz156 reviewed
![image](https://user-images.githubusercontent.com/106965005/223415796-ac01a63b-4302-4a17-a7d5-b950fb308df7.png)

2023-03-07 11:59 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
>          }
테스트 클래스 간에 중복되는 코드가 있으면, 상위 클래스로 옮겨서 상속하는 방식으로 하는 것이 나을까요?

2023-03-08 02:47 UTC, Hyune-c requested changes

2023-03-08 02:47 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/ResultCountService.java
> +                        new ConcurrentHashMap<>(Map.of("strike", 0, "ball", 0));
- strike, ball 이 string 으로 들어가 있네요. 네이밍이 바뀌면 까먹지 않고 수정해줘야 합니다.
- strike, ball 과 같은 result 가 추가/제거될 때마다 초기화 로직을 수정해줘야 합니다.
- 무엇에 대한 result 인가요?

지금의 코드에 대해 위 내용을 어떻게 생각하시나요?

2023-03-08 02:47 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/ResultCountService.java
> +    }
불변에 대해 학습해주세요.
hint. unmodifiableMap

2023-03-08 02:47 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
이 코드는 기능적으로는 문제가 없지만, 유지보수 관점에서 매우 심각한 문제를 가지고 있습니다.
어떻게 생각하시나요?
hint. 부수 효과, 참조 투명성

2023-03-08 08:07 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/service/ResultCountService.java
> +                        new ConcurrentHashMap<>(Map.of("strike", 0, "ball", 0));
- 변화에 대응하기 어렵고, 네이밍을 봤을 때, 어떤 코드인지 이해하기 어려운 코드를 작성한 것 같습니다. 
- 멀티 스레드 환경을 고려했을 때, map을 클래스 변수로 두는 것은 옳지 못한 생각인거 같습니다.

2023-03-08 08:10 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
멀티 스레드 환경에서, 클래스 변수로 할당된 map을 매개 변수로 받고 map의 값을 변경하면, 스레드간 map의 값이 공유되기 때문에 문제를 야기할 것 같습니다.

2023-03-08 08:55 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
>          }
보통 중복되는 코드는 좋지 않다고 말합니다.
하지만 테스트에서는 재사용보다는 유연함이 중요하다고 생각하기에 괜찮다고 봅니다.

- 혹여 중복을 줄일지라도 상속은 사용하지 않습니다.
- 테스트 준비를 위한 객체를 생성하는 것이라면 픽스쳐를 생각합니다.

2023-03-08 09:08 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
이 코드는 2개의 문제가 있습니다.

- 네. `RESULT_COUNT` 는 클래스 변수이기에 동시성에 취약합니다.
- 힌트를 다시 한번 봐주세요.

2023-03-08 10:08 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
- 위 코드는 RESULT_COUNT라는 외부 요인을 변경시기키 때문에 부수 효과가 있다고 할 수 있을 것 같습니다. 
또한 외부 상태에 의존하므로 참조 투명하다고 볼 수 없습니다.

내용은 이해가 가지만, 어떻게 구성해야 할 지는 리팩토링하면서 구체적으로 구현을 해보아야 더 잘 이해할 것 같습니다.

2023-03-08 21:02 UTC, choizz156 reviewed
- 기존에 map에 데이터를 저장하는 방식에서 변경하여, BattingResultCount라는 클래스를 만들어 인스턴스 변수에 데이터를 저장하고, 변경시키는 메서드를 만들었습니다.

-  유저들이 배팅을 시작할 때마다 BattingResultCount 객체가 생성되어 타격 결과에 따른 카운트를 객체에 저장합니다.



- 이 클래스를 map형식의 데이터 레이어 계층을 만들어 저장할 생각을 했습니다.

----
코드를 리팩토링하다 보니 참조 투명성을 갖는 메서드를 만들기가 많이 힘든 것 같습니다. 
특히, 데이터를 변경해야하는 경우 ,인스턴스 변수를 변경하는 방법밖에 떠오르지 않았습니다. 
그래서 setter속성의 메서드를 만들어 부수효과를 일으키는 메서드를 만들 수 밖에 없었습니다.

2023-03-08 21:02 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResultCount.java
> +    }
인스턴스 변수를 변경해야 하다보니 setter 속성을 가진 메서드가 등장했습니다. 
이렇게 되면, 부수 효과가 생겨, 좋은 메서드라고 할 수 없을 것 같습니다.


- 가변 데이터를 다뤄야 할 때, 클래스의 인스턴스 변수를 변경시키려면, 
불변 객체를 만들기 힘들고, 부수 효과를 일으키는 함수를 만들 수 밖에 없을 것 같은데 다른 방법이 있을까요?

2023-03-09 06:33 UTC, Hyune-c requested changes

2023-03-09 06:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +                            .build();
`nit` builder 의 단점에 대해 알고 계신가요?

2023-03-09 06:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResultCount.java
> +    }
OOP 는 상태를 관리하는 것이 자연스지만, FP 는 결이 조금 다르기에 발생하는 인지 부조화 입니다.
두개의 패러다임 중 어느 것이 옳다는 아니기에 이것들은 좀 더 공부해보시기를 추천합니다.

> hint
1. kotlin 은 함수형 언어가 아니다. 함수 지향 언어이다.
2. datasource 는 어느 레이어에, 어느 역할로 있어야 될까.

2023-03-09 06:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
`nit` 클래스 네임을 그대로 따르고 있군요. 만약 DB 가 운영되는 중에 아래와 같은 요구 사항이 들어오면 어떻게 될까요?

1. STRIKE 로 바꿔주세요.
2. Striek 로 바꿔주세요.

2023-03-09 06:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingResultCountService.java
> +        BattingResultCount battingResultCount = BattingResultCount.getInstance();
굳이 객체를 생성해야 될까요?
hint. db 는 같은 값을 복수의 개인에게 저장할 때 어떻게 할까요?

2023-03-09 06:33 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/BattingResultGenerator.java
> +    }
두번째 생성자는 왜 필요한 것일까요?

2023-03-09 08:44 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +                            .build();
위 코드에 변수가 추가되어도 컴파일 오류가 나지 않아 변수에 null이 리턴될 수 있을 것 같습니다.

2023-03-09 08:46 UTC, choizz156 commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/BattingResultGenerator.java
> +    }
일반 야구 level1에서 필요한 타격 결과와 우주야구 level1에서 필요한 타격 결과가 달라서 2개를 만들었습니다.

2023-03-09 08:48 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
따로 상수 변수를 만드는 것이 변화에 대응하기 수월할 것 같습니다.

2023-03-09 08:58 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +                            .build();
네. 가장 나쁜 에러인 런타임 에러가 발생할 수 있고, 인적 오류를 일으킬 수 있습니다.
참고 내용을 전달 드립니다.

https://hyune.gitbook.io/hyune-wiki/computer-science/design-pattern/builder-pattern

2023-03-09 08:58 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/Strike.java
> +    }
네. 조금 극단적인 예시였습니다. 사실 저런 요구사항인 경우에는 마이그레이션도 해야되죠..
그래서 enum 과 db 값을 이원화해서 관리하는 방법도 있습니다.

지금의 방법도 나쁘지 않습니다. 
하지만 이것은 학습이기에 많은 케이스를 `인지` 하시고 지금에 맞는 합리적인 안을 `선택` 하시면 됩니다.

2023-03-09 08:58 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/BattingResultGenerator.java
> +    }
- 지금의 일반야구 lv1 은 우주야구 lv1 의 부분집합 or 필요조건이 아닙니다. 완전히 달라진 요건입니다.
- 좀 더 일반적인 예를 들자면
    - 동전만 받을 수 있는 자판기를 개발하고, 테스트 케이스를 만들었는데
    - 업무가 완전히 바뀌어 동전은 폐기되고, 지폐만 받을 수 있는 자판기로 바뀌었다면?
    - 동전에 대한 테스트 케이스를 유지할 필요가 있을까?
    - 심지어 prod 코드에 영향을 주면서까지?

이것은 제가 이전 설명을 모호한게 한 것 같습니다. 
아마 이전의 테스트 케이스를 만족해야된다고 해서 유지하신 것 같아요.
위 내용을 참고하시어 만족스럽지 못한 테스트는 ignore 시키셔도 될 것 같습니다.

2023-03-09 23:08 UTC, choizz156 reviewed
- double ball을 추가하였습니다.
-------
 앞선 수업에서 말씀해주신 힌트를 적용하려고 노력해봤습니다. 

 우선, api를 2가지로 분리했습니다.

- 먼저 타석이 시작일 경우, api를 따로 만들었습니다.
 타격 카운트를 저장하는 객체를 생성 후 id를 부여하여 map 저장소에 (id, 객체)를 저장하도록 했습니다.

- 그리고 타자가 다음 타격을 할 경우, api에 id를 path variable로 넣고 map 저장소에서 id를 통해 엔티티를 찾은 뒤 그 엔티티의 카운트를 조작하는 방식입니다.

----

혹시 계층형 아키텍쳐에 대해 참고할 만한 책이 있을까요??

2023-03-10 05:23 UTC, Hyune-c approved these changes
API 메서드 외, 기능상 큰 문제는 없습니다.
더 이상 길어지지 않기 위해 approve 합니다.

---

> 혹시 계층형 아키텍쳐에 대해 참고할 만한 책이 있을까요??

저도 계층형 아키텍처는 블로그로 공부한지라 책은 잘 모르겠어요.
링크드린 것과 `양파 아키텍처` 로 검색해보시면 조금 더 도움이 될 것 같습니다.

2023-03-10 05:23 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +    }
GET 메서드는 어떤 경우에 사용해야 된다고 생각하시나요?

2023-03-10 05:23 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/BattingResultCountMapDao.java
> +    private final AtomicLong number = new AtomicLong(0);
`nit` ConcurrentHashMap 을 사용한다면 굳이 AtomicLong 까지 쓸 필요가 있을까요?
ConcurrentHashMap 의 maxId 를 가져오는 형태로 대신할 수 있을 것 같습니다.

2023-03-10 05:23 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>      }
`nit ` 
controller 는 service 의 조합으로 구성되기에 지금의 모습도 나쁘지 않습니다.
하지만 `updateBattingResultCount` 는 사실상 repository 수정만 일어나기에 이것까지 controller 에서 해줘야되나? 라는 느낌이 듭니다.

저는 batting 이라는 하나의 메서드에서 모두 일어나야 되는 일처럼 느껴집니다.

2023-03-10 05:23 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResultCount.java
> +    }
- count 가 setCount 의 매개변수로 존재해야 되나요?
- `nit` addCount 가 setCount 를 호출하는 형태라.. 조금 어색한 느낌이 듭니다.
- `nit` 개인적으로 switch 는 return 과만 활용하는 편입니다. break 는 어색하더라구요.

2023-03-10 11:02 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +    }
서버에서 데이터를 가지고 올 때 주로 사용하는데, 
생각해보니 http 바디 값으로 보낼 데이터가 없고,  항상 같은 데이터를 가지고 오는데 get을 쓰면 안될까요?

2023-03-10 11:38 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/BattingResultCountMapDao.java
> +    private final AtomicLong number = new AtomicLong(0);
`/batting/start`로 요청을 할 때마다 map에 id와 함께 객체가 저장되는데, 
저장될 때 마다 id값을 증가시켜 저장해야 사용자마다  각각의 id를 부여하여 할 수 있다고 생각을 했습니다.
그리고 AtomicLong을 사용하면, 스레드 세이프하다고 생각을 했습니다.

maxId를 사용하면, 한 명의 유저가 사용한다는걸 전제로 말씀을 해주신 건지 궁금합니다!

2023-03-11 09:42 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/BattingResultCountMapDao.java
> +    private final AtomicLong number = new AtomicLong(0);
사용자마다의 id 하면 지금 생각하신 방법이 맞습니다.
저는 db pk 생성 방법 중 하나인 auto increment 를 의도하신 건줄 알았어요.

2023-03-11 09:48 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +    }
https://datatracker.ietf.org/doc/html/rfc7231#section-4.3

이쯤에서 rfc 를 한번 읽어보시면 좋을 것 같네요.
간략히 말하면 메서드는 `param, body 의 유무가 아닌 해당 리소스를 기준으로 기대되는 결과` 에 가깝습니다.

2023-03-12 03:07 UTC, merged