일반 야구 level2
Programmers-Hyune-c/cosmic-baseball-init pull request #47
Opened 2023-03-12 03:09 UTC by choizz156

일반 야구 level2 구현했습니다. 

- 타격 결과는 enum 값으로 다시 대체하였습니다. 
- 새로운 타석 api를 추가하고 예외 처리 로직을 추가했습니다.

2023-03-12 03:15 UTC, choizz156 reviewed
![image](https://user-images.githubusercontent.com/106965005/224522172-7d3e876b-827d-433f-9989-910479a4e3d4.png)

2023-03-12 12:57 UTC, Hyune-c requested changes

2023-03-12 12:57 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv2Test.java
> +        totalResult.setBattingTotalResult(BALL);
getter, setter 는 이미 보편적인 사용법이 알려진 네이밍입니다.

-  set 이라는 네이밍은 매개변수의 상태로 변경하는 것이 보편적인 사용법입니다.
- 이전의 상태에 변화를 더하는 것이 아닙니다.

2023-03-12 16:46 UTC, choizz156 reviewed
- 피드백 반영하여 명칭을 변경했습니다.
-  메서드 역할을 분리하여 타격 결과, 카운트 증가, 타석 결과 메서드로 분리했습니다.

2023-03-13 02:09 UTC, Hyune-c requested changes

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/TotalBattingResultMapDao.java
> +    private final Map<Long, TotalBattingResult> store = new ConcurrentHashMap<>();
네이밍을 적절히 축약한 것이 좋네요. 👍
클래스 네이밍 덕분에 꽤 직관적입니다.

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/TotalBattingResultMapDao.java
> +    }
- jpa entity 사용에 대해 persist 와 merge 의 차이를 학습해주세요.

지금 당장 고쳐야될 정도로 심각한 것은 아니지만 위험성이 내포되어 있습니다.

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
> +    private final int battingResultCount;
`nit` 
직역하면 `배팅 결과의 숫자` 이군요. 
조금 더 생각해보면 increase 의 의미도 넣을 수 있지 않을까요?

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
>  }
`nit` 개인적으로 생성자나 getter 정도는 클래스 레벨에 사용합니다.

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +public class TotalBattingResult {
JsonInclude 가 어떤 역할을 하고 있는지는 이미 알고 계실 것 같습니다.
그렇다면 그 역할은 어느 레이어에서 해야될까요?

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
getInstance() 라는 네이밍에 대해 어떻게 생각하시나요?

2023-03-13 02:09 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/exception/controller/ExceptionController.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
5xx 는 의도적으로 반환하는 에러가 아닙니다.

2023-03-13 02:09 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
>      }
init 에 어울리는 어노테이션은 BeforeAll 같습니다.

2023-03-13 04:45 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
싱글톤 패턴에서 정적 메서드로 객체를 가지고 올 때 사용하는 네이밍인 것 같습니다.
생각해보니, 굳이 필요없는 메서드인 것 같습니다.

2023-03-13 04:50 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +public class TotalBattingResult {
생각을 해보니, 응답 객체에서 사용을 해야할 것 같습니다.

2023-03-13 10:32 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +public class TotalBattingResult {
ResponseDto 는 범용 dto 로 보입니다. 따라서 적절합니다.
`nit` 개인적으로는 정상 응답은 그냥 내려주는 편 입니다.

2023-03-13 10:32 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
> instance 혹은 getInstance
> (매개변수를 받는다면) 매개변수로 명시한 인스턴스를 반환하지만, 같은 인스턴스임을 보장하지는 않는다.

이펙티브 자바에 있는 내용이긴 하지만, 저도 싱글톤 패턴에 좀 더 어울리는 네이밍이라고 생각해서 사용하지 않습니다.

2023-03-13 12:14 UTC, choizz156 reviewed
### persist 와 merge 차이

- detached된 엔티티가 다시 영속화 될 때, `merge`가 발생합니다. 
update 로직이 실행 될 때, merge가 발생한다고 가정을 하면,
파라미터로 들어오는 엔티티의 복사본을 영속화시키고 그 영속화된 복사본을 반환하기 때문에 
파라미터로 들어온 엔티티와 반환되는 엔티티는 동일한 엔티티가 아니게 됩니다.
따라서, 영속화된 값을 리턴하고 사용해야합니다.

- 준영속 상태의 엔티티를 영속화 할 때, `persist`가 발생합니다.
 save 로직을 수행할 때, persist가 발생한다고 가정하면,
파라미터로 들어온 객체 자체를 영속화 시키고 반환하기 때문에 
파라미터와 반환되는 엔티티는 동일한 엔티티입니다.

2023-03-14 03:45 UTC, Hyune-c requested changes

2023-03-14 03:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>      }
start 와 new 가 달라야만 할까요?

2023-03-14 03:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dao/TotalBattingResultMapDao.java
> +    }
`nit` 너무 어려운 내용인 것 같으니 언급만 하고 넘어가겠습니다.

---

merge 와 persist 의 관점에서 고민해주세요.

- save 와 update 는 사실상 같은 로직이네요.
- update 의 매개변수 id 의 동시성 방지가 service 에 있는게 적절한가?

2023-03-14 03:45 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
>      }
setUp 도 init 과 같아 보입니다. setupEach, setupEvery 등의 네이밍이 조금 더 명확합니다.
사실 저는 테스트 코드 쪽 네이밍은 별로 신경 안쓰는 편입니다.

```java
    @BeforeEach
    void beforeEach() {
        container = new TotalBattingResult();
    }
```

2023-03-14 03:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
이 숫자들은 enum 에 있어야 합니다.

`nit` 나아가서는 이 메서드는 2개로 분리할 수 있습니다.
- add count 를 가져오는 행위
- add 행위

2023-03-14 06:07 UTC, choizz156 reviewed
피드백 반영하여 리팩토링 해보았습니다!

persist와 merge는 조금 더 고민해보겠습니다!

2023-03-15 01:46 UTC, Hyune-c approved these changes

2023-03-15 01:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
> +    private final int increasingCount;
`nit`
조금 더 발전시키자면, increaseStrikeCount 와 increaseBallCount 를 동시에 관리할 수 있을 것 같습니다.

2023-03-15 01:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
`nit` 
is3Strike 는 내부 구현이 너무 드러나기에 isOut 으로 추상화하는 형태가 더 적절하다고 생각합니다.
out 이 되기 위한 strike count 는 5로 늘어날 수도 있으니까요.
하지만 이번 범위를 넘어간다고 생각하여 nit 합니다.

2023-03-15 01:46 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
`addBattingResultCount` `resetCount` 네이밍의 일관성이 떨어진다고 생각합니다.

2023-03-15 04:51 UTC, merged