우주야구 레벨 2
Programmers-Hyune-c/cosmic-baseball-init pull request #49
Opened 2023-03-17 00:18 UTC by choizz156

어제 수업 내용을 듣고 확률 테스트는 ci시 ignore하는 것이 맞다고 생각하여 ignore했습니다!

2023-03-17 00:20 UTC, choizz156 reviewed
![image](https://user-images.githubusercontent.com/106965005/225780471-86eb7dfb-91c2-4639-ac0e-7b465d7640a1.png)

2023-03-17 14:37 UTC, Hyune-c requested changes

2023-03-17 14:37 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +        this.strikeCount += battingResult.getIncreaseStrikeCount();
enum 은 이제 2가지 상태를 가집니다. 그렇다면 이 메서드는 줄일 수 있지 않을까요?

2023-03-17 14:37 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingService.java
> +    }
ordinal 은 상당히 위험합니다.
BattingResult 에게 묻는 방식을 권장합니다.

2023-03-17 14:37 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv1Test.java
> +        BattingResult result = BattingResult.values()[RANDOM.nextInt(5)];
저는 5라는 숫자가 무엇인지 모르겠습니다.

2023-03-17 14:37 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv2Test.java
>      }
`nit` 거의 유사한 로직이 반복되고 있네요. 고민해볼만 합니다.

2023-03-18 04:26 UTC, choizz156 reviewed
피드백 반영하여 리팩토링 해보았습니다!

2023-03-18 17:45 UTC, Hyune-c requested changes

2023-03-18 17:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/BattingResult.java
>      }
`nit` 재미있는 메서드네요.
기능을 생각해보면 toBullEyeResult() 도 고민할만한 네이밍입니다.

2023-03-18 17:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
>      }
`nit` 굳이 테스트용이라는 주석이 필요할까요? 

`nit` ballCount, strikeCount 가 primitive 형이라 0이 들어가니까 NoArgsConstructor 를 활용하신 것 같습니다.
만약 생성 책임을 분리하는 방법을 활용한다면 NoArgsConstructor 를 활용하지 않아도 됩니다.

2023-03-18 17:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
>      }
이전 로직에서 isHit가 빠졌네요. 의도적인건가요?
그리고 judgeBatterStatus 메서드의 네이밍은 `판단` 인데, `변경` 하고 있네요.

2023-03-18 17:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +    public static final Random RANDOM = new Random();
드디어 Random 이 하나의 클래스로 속하게 되었군요. 👍

하지만 이것이 public 이어야 할까요? 클래스 변수의 노출은 매우 위험합니다.
예외적으로 util 성격은 노출하기도 하지만, 이 클래스는 util 이라기에는 기능이 특화되어 있습니다.

2023-03-18 17:45 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +        }
커밋 전에 코드 전체의 컨벤션 체크를 (린트) 습관화해주세요.

2023-03-18 17:45 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv2Test.java
> +    @Disabled("CI 시 확률 테스트는 ignore 합니다.")
`nit` 
문구가 조금 이상하네요. 마치 CI 에서만 ignore 된다는 것 처럼 읽힙니다.
항상 ignore 되는 것 아닌가요?

2023-03-18 17:45 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv2Test.java
>          totalResult.judgeBatterStatus();
이전의 리뷰와 같습니다. 네이밍을 보면 `판단`만 할 것 같지만, 실제로는 `변경`하고 있습니다.

2023-03-19 10:25 UTC, choizz156 reviewed
피드백 반영하여 리뷰요청드립니다!

2023-03-19 10:25 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +        return new TotalBattingResult(strikeCount,ballCount);
테스트용으로 객체를 생성하는 메서드를 만드는 것에 대해 어떻게 생각하시는지 궁금합니다!

2023-03-19 10:25 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
>      }
isHit로직은 isGoToBase()에 넣었습니다!
```java
 private boolean isGoToBase() {
        return this.ballCount >= 4 || this.battingResult == HIT;
    }
```

2023-03-19 10:25 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +        }
isBullEyeResult 메서드에서 사용하는 private 메서드라 이런 식으로 컨벤션을 했는데
이렇게 하는 것은 별로일까요?

```java
 private boolean isBullEyeResult(BattingResult result) {
        return isStrikeOrBall(result) && getRandomResult() == result;
    }

        private boolean isStrikeOrBall(BattingResult result) {
            return result == BALL || result == STRIKE;
        }
```

2023-03-19 13:51 UTC, Hyune-c requested changes

2023-03-19 13:51 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +        }
제 생각은 별로 중요하지 않습니다.
중요한 것은 지금과 같이 수동으로 들여쓰기를 하는 것이 `일반적인` 포맷팅 컨벤션에 맞지 않다는 것입니다.

예를 들어 이 파일에서 `Reformat Code` 를 하면 들여쓰기가 없어질 것입니다.
그렇다면 동료가 이 파일을 수정하고 

- `Reformat Code` 를 하지 않거나
- `Reformat Code` 후에 저 부분만 다시 원상복구 해야 될까요?

linter 와 정적 분석의 필요성에 대해 학습해주세요.

---

개인적으로는 굳이 들여쓰기로 구분하지 않아도 private 메서드라는 점에서 충분히 이해가 될 것 같습니다.
필요하다면 주석을 넣거나, 더 필요하다면 클래스를 분리할 것입니다.

```java
    private boolean isBullEyeResult(BattingResult result) {
        Boolean isStrikeOrBall = (result == BALL || result == STRIKE);
        Boolean isTheSameResultOneMore = (getRandomResult() == result);
        
        return isStrikeOrBall && isTheSameResultOneMore;
    }
```

오직 한 곳에서만 쓰인다면 응집시키는 것도 방법입니다.

2023-03-19 13:51 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +        return new TotalBattingResult(strikeCount,ballCount);
https://hyune.gitbook.io/hyune-wiki/programmers/undefined#undefined-1

내용을 따로 정리했습니다.

> 추가 키워드
- private 메서드는 어떻게 테스트하나요?
- fixture, stub

2023-03-19 13:51 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
>      }
update 를 함에 있어 값을 전달받는 것이 아닌 내부의 값들을 가지고 재조립하게 되어 있네요.
이것에 대해 어떻게 생각하시나요?

hint. 재조립을 하는 시점이 언제여야 되는가? 
- 재조립 메서드를 호출하기 위한 값을 저장하는 시점?
- 재조립 메서드를 호출하는 시점?

---

이 메서드는 명시적으로 update 를 말하고 있습니다.
즉 무조건적으로 어떤 변화가 생길 것으로 기대됩니다.
하지만 로직을 보면 아무런 변화도 생기지 않는 케이스가 있습니다.

2023-03-19 13:51 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
리뷰가 거듭될수록 클래스의 loc 가 줄어들고 있네요.
처음의 코드와 리뷰가 끝난 시점의 코드를 꼭 비교해봐주세요.
아마 본 교육에서 경험한 것 중 가장 큰 학습이 되실겁니다.

2023-03-19 13:51 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingService.java
> +    ) {
혹시 이 부분 `Reformat Code` 하면 들여쓰기 없어지지 않나요?

2023-03-20 03:28 UTC, choizz156 reviewed
```update 를 함에 있어 값을 전달받는 것이 아닌 내부의 값들을 가지고 재조립하게 되어 있네요.
이것에 대해 어떻게 생각하시나요?

hint. 재조립을 하는 시점이 언제여야 되는가?

재조립 메서드를 호출하기 위한 값을 저장하는 시점?
재조립 메서드를 호출하는 시점?
```
값을 저장하는 시점에 재조립을 해야한다고 생각합니다.

타격 결과, 카운트 증가, 타석 상태 조정이 동시에 일어나야 된다고 생각을 했는데, 메서드 명을 추상화하기가 쉽지가 않아서 메서드를 나누어서 만들었습니다..

그래서 일단 최대한 추상화된 메서드명으로 3개의 과정을 합쳤습니다!

2023-03-20 07:08 UTC, Hyune-c approved these changes
지금까지 했던 PR 중에서 가장 많은 학습이 되신 PR 로 생각됩니다.
잠시 개발을 멈추고 본 PR 에서 얻은 것과 생각을 정리해보시는 것을 권장합니다.

2023-03-20 07:08 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
private 생성자와 public 정적 팩토리 메서드 조합 좋네요. 👍
사실 개인적으로는 귀찮아서 잘 안하는 편 입니다. 코틀린의 부생성자 기능에 익숙해지다보니..

2023-03-20 07:08 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    }
이제 매개변수와 update 행위가 자연스럽게 이어지네요. 👍
`nit` 개인적으로는 이정도 크기가 되면 메서드를 하나로 합치는 편입니다.

`nit` 지금의 방법은 OOP 의 관점에서 적절합니다. 하지만 좀 더 나아가는 방법도 있습니다.
hint. 상태 변화가 없는 객체란?

2023-03-20 07:08 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv2Test.java
> +        TotalBattingResult totalResult = TotalBattingResult.of(0, 0);
꽤 직관적인 fixture 생성을 할 수 있게되었네요. 👍

2023-03-20 12:25 UTC, merged