일반 야구 레벨 3
Programmers-Hyune-c/cosmic-baseball-init pull request #50
Opened 2023-03-22 12:32 UTC by choizz156

일반 야구 레벨 3 구현해 보았습니다!

2023-03-22 12:39 UTC, choizz156 reviewed
![image](https://user-images.githubusercontent.com/106965005/226907157-d2a58599-b1c5-4e42-9644-0904abb8faac.png)

2023-03-23 14:03 UTC, Hyune-c requested changes
> 예외 처리를 할 때, 비지니스 로직과 관련된 예외 처리를 컨트롤러에 오기 전에 필터나 인터셉터를 사용해서 해도 될까요?
예를 들어, 3out을 미리 인터셉터나 필터로 체크해서 예외 처리를 하는 것은 별로일까요?

- 인터셉터와 필터는 어떻게 다른가요?
- 각각 통상적으로 사용되는 용도, Best Practice 가 어떻게 되나요?

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +
이 로직이 호출 될 수 있나요? bean validation 을 활용할 수 있을 것 같습니다.

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
bean validation 을 활용하기로 했다면 좀 더 정리할 수 있을 것 같습니다.

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/ScoreBoard.java
베이스가 15개가 되면 어떻게 하실건가요?
이 고민에 따라 내부가 많이 바뀔 것 같습니다.

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    private final ScoreBoard scoreBoard = ScoreBoard.of(false, false, false);
`초기 상태` 라는 것을 좀 더 명시적으로 표현할 수 있지 않을까요?

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/exception/ErrorResponse.java
>      }
private 생성자에서의 builder 사용 좋네요. 👍

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/exception/ExceptionType.java
> +    }
`nit` 
lombok 을 활용할 수 있을 것 같습니다.
만약 활용하지 않더라도 접근 제한자의 누락은 조금 어색합니다.

2023-03-23 14:03 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +        BattingResult target = BattingResult.valueOf(targetResult);
이 라인에 대해서 어떻게 생각하시나요?

2023-03-24 06:58 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +        BattingResult target = BattingResult.valueOf(targetResult);
dto에서 들어오는 targetResult를 String 타입이 아닌 enum타입으로 바꿨습니다.

2023-03-24 07:07 UTC, choizz156 reviewed
> 인터셉터와 필터는 어떻게 다른가요?
- 필터는 디스패쳐 서블릿을 통과하기 전과 요청이 끝나고 디스패쳐 서블릿 통과 후에 작동을 합니다.
(서블릿에서 제공)
- 인터셉터는 디스패쳐 서블릿을 통과한 후 컨트롤러 사이에서 작동합니다. (스프링에서 제공)

> 각각 통상적으로 사용되는 용도, Best Practice 가 어떻게 되나요?
- 통상적으로
  - 필터는 이미지나 데이터 압축이나, 보안 등 공통적인 작업에서 사용됩니다.
  - 인터셉터는 api 호출, 인증/인가 관련해서 작동합니다. 
- Best Practice
  - 혹시  Best Practice를 찾는 사이트나 검색 키워드 같은 것이 있을까요?? 검색해도 잘 나오질 않습니다..

2023-03-24 07:41 UTC, Hyune-c commented
> 각각 통상적으로 사용되는 용도

- 제가 아는 것과 조금 다른 점이 있군요. 인터셉터와 필터에 대해 얘기하면서 해결해보겠습니다.

`nit` logging 은 어디에 있으면 좋을까요?

> 인터셉터와 필터는 어떻게 다른가요?

- 이번에는 web server 와 was 에 차이에 대해서 조사해주세요.
- 그리고 4종류를 동시에 생각해서 어떤 공통점이 있고 차이점이 있는지 생각해봐주세요.

> 혹시 Best Practice를 찾는 사이트나 검색 키워드 같은 것이 있을까요??

- 딱히 없는거 같아요. 베스트 프랙티스는 그냥 평소에 블로그나 커뮤니티를 자주 보는 수밖에 없을 것 같습니다.

2023-03-24 13:43 UTC, choizz156 reviewed
> 이번에는 web server 와 was 에 차이에 대해서 조사해주세요.
- webserver는 was를 거치지 않고 정적 리소스 반환하는 역할을 합니다.
- was는 동적인 컨텐츠를 제공하기 위해 사용합니다.(로직 처리)

> 4종류를 동시에 생각해서 어떤 공통점이 있고 차이점이 있는지 생각해봐주세요.

filter와 interceptor는 요청에 대해 어떠한 처리를 할 수 있다는 공통점이 있습니다.
반면, 요청의 처리 위치가 filter는 webserver에서 이루어 지고, interceptor는 was내의 spring 환경에서 이루어집니다.

interceptor는 컨트롤러로 들어가는 데이터를 가공하는데 사용할 수 있다는 점에서 was와 공통점이 있는 것 같습니다. 반면에, filter는 was로 들어가기전 공통 처리(?)에 사용할 수 있다는 점에서, webserver와 공통점을 갖는 것 같습니다.
> logging 은 어디에 있으면 좋을까요?

만약 로깅을 하는데 어떠한 로직이 들어간다면(예를 들어, 어떠한 경우는 로깅을 하고, 어떤 경우는 안하고) 인터셉터에서 로깅을 하는 것이 좋을 것 같은데, 로직이 없어도 굳이 필터에서 할 필요는 없을 것 같습니다.

2023-03-24 14:27 UTC, Hyune-c requested changes
> 통상적으로
필터는 이미지나 데이터 압축이나, 보안 등 공통적인 작업에서 사용됩니다.
인터셉터는 api 호출, 인증/인가 관련해서 작동합니다.

> interceptor는 컨트롤러로 들어가는 데이터를 가공하는데 사용할 수 있다는 점에서 was와 공통점이 있는 것 같습니다. 반면에, filter는 was로 들어가기전 공통 처리(?)에 사용할 수 있다는 점에서, webserver와 공통점을 갖는 것 같습니다.

- 위 내용에 따르면 인터셉터에서 처리되어야 하는 인증/인가는 was 에서 처리되어야 합니다?
- 인증/인가와 보안은 상호 어떤 관계인가요?
- 추가 키워드. nginx, 포트 포워딩, cdn

위 내용에 대해 생각해주세요.

---

- 필터, 인터셉터, AOP
- 웹서버, was
- AWS 의 기능들

이것들을 다 같이 이야기 하실 수 있으면 더 좋습니다.

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>  }
status 를 string 으로 받아야만 하나요?

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/ScoreAndBaseBoard.java
> +    private int baseNumber;
baseNumber 가 1루, 2루, 3루의 뜻인가요?
만약 맞다면 `onBaseList.size() + 1` 으로 대체 가능하지 않을까요?

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/ScoreAndBaseBoard.java
> +public class ScoreAndBaseBoard {
`nit` And 라는 단어가 들어가는 클래스라..
2가지 역할을 동시에 한다는 느낌이 듭니다.

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
> +    private final ScoreAndBaseBoard scoreAndBaseBoard = new ScoreAndBaseBoard();
- `TotalBattingResult` 전체 배팅 결과
- `ScoreAndBaseBoard` 점수와 진루 상황

배팅 결과가 점수와 진루의 일부일까요.
점수와 진루가 배팅 결과의 일부일까요.

지금의 객체 설계는 `점수와 진루가 배팅 결과의 일부` 입니다.

---

이것은 객체 설계를 할 때 어떤 아이디어를 가지고 있느냐의 차이입니다.
저는 어색함이 느껴지기는 하지만, 충분한 이야기가 할 수 있다면 지금도 나쁘지 않습니다.

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/TotalBattingResult.java
>      private BattingResult battingResult;
클래스명은 TotalBattingResult 인데, 단일 BattingResult 가 상태로 있습니다.
클래스의 네이밍으로 보면 Collection 이 있어야 자연스럽지 않을까요?

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/exception/ExceptionType.java
> +    NEW_BATTING("타석이 진행 중 일때, 새로운 타석은 불가능합니다."),
NEW_BATTING 은 `새로운 배팅`으로 직역 됩니다.
`타석이 진행 중이다.` `새로운 타석은 불가능하다.` 라는 뜻은 보이지 않습니다.

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +    public static BattingResult getBattingResult(int percentage, BattingResult target) {
```java
RandomBattingResultGenerator.getBattingResult()
RandomBattingResultGenerator.get()
```

역할을 충분히 한정했다면 축약할 수 있다고 생각합니다.

2023-03-24 14:27 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/RandomBattingResultGenerator.java
> +    }
`nit` 
코틀린의 확장 함수를 활용하면 좀 더 가독성 좋게 수정할 수 있습니다.
하지만 자바에서는 좋은 해결 방법이 떠오르지 않네요.
 
간간히 코틀린의 아이디어에 대한 글을 보시면 좋은 인사이트를 얻으실 것 같습니다.

2023-03-26 08:17 UTC, choizz156 reviewed
- 인증/인가와 보안은 상호 어떤 관계인가요?
    - 인증 : 신원 확인 목적, 사용자가 본인이 맞는지 확인하는 절차. 회원인지 아닌지..(로그인),
    - 인가: 권한 부여 목적, 어떤 리소스에 접근이 가능한지를 식별한다.
    
    spring security의 경우, 인증을 완료하면 spring context에 인증 정보가 담기고, 그곳에 어떤 리소스에 접근할 수 있는 권한(user role) 또한 저장할 수 있습니다. 따라서, 한 번 인증을 하면, 그 후 요청은 따로 권한 부여를 할 필요없습니다. 즉, 인증 프로세스에서 요청에 따른 응답과정에 인가와 관련된 부분이 포함되어 있다는 점에서 인증과 인가는 동시에 수행된다고 볼 수 있을 것 같습니다.
    
    그런데, spring security의 경우 인증과 인가에 대한 과정은 filter를 이용해서 수행을 하는데, 이렇게 생각해보면, 인증/인가는 필터 단에서 수행을 해도 문제가 되지 않는 것 같습니다.
    
    보안 또한 위부 공격으로부터 애플리케이션을 보호하기 위해선 was에 접근하기 전인 filter에서 수행해도 될 것 같습니다.
    
    만약 aws를 사용한다면, 필터가 아닌  aws에서 보안 구성을 할 수 있을 것 같습니다.(security group, 망분리, vpn, 방화벽 등등)

말씀해주신 추가 키워드들과 aop는 필터와 인터셉터와 연결짓기가 열려워 조금더 공부를 해봐야할 것 같습니다.

2023-03-26 13:08 UTC, Hyune-c approved these changes
네. 필터와 인터셉터는 스프링에만 관련된 것이 아닙니다.
오히려 더 큰 웹 라이프 사이클을 이해해야 합니다.
너무 많은 내용이 함축되어 있음으로 조금의 키워드를 더 드리는 것으로 넘어가겠습니다.

- spring boot 는 was 를 내장하고 있다.
    - 그리고 가장 단순한 배포에서는 jar 로 할 수 있다.
    - 그렇다면 고전적인 web server 의 역할은 누가 어떻게 하고 있는 것일까?
- 고전적인 web server 의 역할에 대해
    - 정적 리소스 지원
    - gateway 역할
    - 기본적인 보안 (ex. ddos)

2023-03-26 13:08 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>      }
- `POST /new`
- `PATCH /batting/{id}` 

위 두개 API 의 네이밍 의도를 알려주세요.

2023-03-27 02:49 UTC, choizz156 commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>      }
- `POST /new`는 새로운 게임을 시작할 때 사용하는 api를 의도했는데 도메인 네이밍이 변경된 시점에서`/games`로 네이밍을 바꾸는 것이 나을 것 같습니다.
- `PATCH /batting/{id}`는 리소스가 수정된다는 판단에 PATCH를 사용했고, batting 행위가 리소스를 바꾼다는 생각에 이렇게 네이밍을 했었던 것 같습니다. 도메인 네이밍이 변경된 시점에서 이것 또한 `/games/{id}`로 바꾸는 것이 더 나을 것 같습니다.

2023-03-27 03:52 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
>      }
`PATCH /games/{id}`

- 직역하면 게임의 상태를 변경하는 것입니다.
    - 하지만 지금의 API 에는 변경을 명령할 내용이 없습니다. 즉 `어떻게`가 빠져있습니다.
    - ex) `PATCH /posts/{id}` 라면 아마 body 로 contents 를 전달하셨을 것입니다.
- 이런 표현의 한계 때문에 batting 이라는 표현을 추가로 넣어주는 것도 괜찮습니다.
    - 또는 games 의 상태 변화가 batting 밖에 없다고 한정하면 괜찮긴 합니다.
    - 사실 이런 형태의 api 는 실무에서는 거의 없습니다.

2023-03-28 10:27 UTC, merged