우주 야구 level 3
Programmers-Hyune-c/cosmic-baseball-init pull request #51
Opened 2023-03-28 12:47 UTC by choizz156

우주 야구 레벨 3를 구현했습니다.

fever inning에 대한 api를 따로 만들고  fever inning 시 타격 결과 퍼센트는 입력하지 않는 방식으로 구현했습니다.

2023-03-28 12:53 UTC, choizz156 reviewed
![image](https://user-images.githubusercontent.com/106965005/228242236-471f16d4-1c8c-4cb6-a626-16d5253ffafb.png)

2023-03-29 13:50 UTC, Hyune-c requested changes
normal inning 과 fever inning 은 완전히 다른 것이라고 생각해주세요.
그리고 그 variation 이 늘어날 수도 있다고 생각해주세요.

마치 KB 카드와 하나 카드처럼, 카드 종류가 더 늘어날 수 있다고 생각해주세요.

2023-03-29 13:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/contoller/CosmicBaseballController.java
> +    }
`PATCH /batting/fever/{id}`

1. 여기에서 id 는 무엇일까요? 직역하면 battingId 로 보입니다.
하지만 의도는 gameId 아닌가요?

2. validationDto 를 사용자로부터 받는다라.. 이상해보입니다.

2023-03-29 13:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/ScoreBoard.java
> +    public void adjust(BattingResult result) {
linter 를 습관화해주세요.
이런 오류는 맞춤법이 틀림과 같습니다.

2023-03-29 13:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/dto/ValidationDto.java
> +public class ValidationDto {
`무엇을` 검증하는 Dto 일까요?
범용이라고 보기에는 outCount 라는 특화된 값이 있는 것 같습니다.

2023-03-29 13:50 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/CosmicBaseballLv3Test.java
>      }
확률 검증은 따로 할 수 있습니다.
하지만 그렇다면 다른 테스트를 추가해야되지 않을까요?

예를 들면 `fever inning 과 일반 inning 의 안타 확률이 다르다.` 등 좀 더 추상화한 테스트를 만들 수 있다고 생각합니다.

2023-03-29 13:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/ScoreBoard.java
>      }
adjust 를 하면 base 가 +1 되는군요.
진루를 표현하신 것 같은데, 일급 컬렉션을 학습하시면 좋을 것 같습니다.

2023-03-29 13:50 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/domain/ScoreBoard.java
> +    }
객체가 가지고 있는 상태가 판단의 기준이 되어야 하나요?
singleton 의 관점에서 다시 생각해봐주세요.

2023-03-30 10:50 UTC, choizz156 reviewed
fever 이닝 시에도 타격 결과와 확률을 입력받도록 변경하였습니다.

----

멘토님께서는 두 개의 클래스에서 기능은 같지만 매개변수가 다른 메서드가 필요하실 때, 인터페이스에 메서드 정의를 어떻게 하시나요??

예를 들어,
```java
public interface GameService {
    //normalGameService에서 필요
    ScoreBoard batting(Long id, int percentage, BattingResult battingResult);
    //feverGamingService에서 필요
    ScoreBoard batting(Long id);
}
저는 상위 클래스를 만들어서 오버로딩을 하는 방법 밖에 떠오르지를 않습니다.

제가 작성한 코드에서 이렇게 하지는 않았습니다!

```
-----
멘토님 덕분에 정말 많이 배울 수 있었습니다!! 정말 감사드리고 만약 새로운 강의를 런칭하신다면 다시 찾아뵙겠습니다👍

2023-03-30 11:38 UTC, Hyune-c approved these changes
수고하셨습니다. 
마지막 리뷰인 만큼 라인바이라인 리뷰보다는 생각할 점을 드리는 것으로 마무리하겠습니다.

감사합니다.

- fever inning 과 normal inning 의 dao 가 서로 다르네요.
    - 연속된 n 개의 회 중에 일부가 fever 인 것이니 하나의 dao 로 할 수 있지 않을까요?
- OOP 에 심취하다보면 메세지를 전달한다는 것에만 빠져서 객체들이 너무 따로따로 놀게 됩니다.
    - 어쩌면 하나의 클래스에서 절차지향적으로 조립하는 역할을 하는 것이 좋을 수도 있습니다.

---

```java
public interface GameService {
    //normalGameService에서 필요
    ScoreBoard batting(Long id, int percentage, BattingResult battingResult);
    //feverGamingService에서 필요
    ScoreBoard batting(Long id);
}
저는 상위 클래스를 만들어서 오버로딩을 하는 방법 밖에 떠오르지를 않습니다.

제가 작성한 코드에서 이렇게 하지는 않았습니다!
```

- service 와 메서드만 추상화 대상일까요? 매개변수를 dto 로 추상화하는 것은 어떨까요?
- 추상화는 너무 어려울 수 있습니다. 지금은 Facade 패턴을 사용하시는 것도 좋다고 생각합니다.

2023-03-30 11:43 UTC, merged