일반야구 Lv1. 구현
Programmers-Hyune-c/cosmic-baseball-init pull request #52
Opened 2023-04-07 06:57 UTC by Jungeunkim-dev

## 구현 내용
- 타격 결과를 리턴하는 api 구현
- 타격 결과는 strike, ball, hit 테스트 구현
![스크린샷 2023-04-07 오후 3 57 07](https://user-images.githubusercontent.com/67693142/230558298-4aaf9e90-dbbc-4d79-bee9-f2c26fdfc705.png)

## 질문 내용
- [타격 결과는 모두 같은 확률을 가집니다] 테스트를 아래처럼 구현했습니다. 

> - 서비스 로직을 N회 실행
> - 서비스 로직이 리턴하는 안타, 스트라이크, 볼의 횟수 기록
> - 3가지 결과의 확률이 동일한지 확인
> - 3가지 결과의 확률이 0.3으로 동일하도록, 1번째 자리까지 반올림

그런데 테스트 반복 횟수를 작게 설정하면(약 1000회) 테스트가 실패하는 경우가 있었습니다. 
이렇게 랜덤 케이스들을 반복해 확률을 계산하는 방식 대신 다른 방식을 선택해야 할지 궁금합니다.

2023-04-08 01:33 UTC, Hyune-c requested changes
> 그런데 테스트 반복 횟수를 작게 설정하면(약 1000회) 테스트가 실패하는 경우가 있었습니다.
이렇게 랜덤 케이스들을 반복해 확률을 계산하는 방식 대신 다른 방식을 선택해야 할지 궁금합니다.

확률 테스트는 모수가 아무리 많아도 근접할 뿐, 정확한 값은 나오지 않습니다.
좀 더 고민해보시고 자세한 것은 라이브 세션 시간에 얘기하겠습니다.

2023-04-08 01:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/controller/BattingController.java
> +        return new ResponseEntity<>(result, HttpStatus.OK);
`keyword` RestController, ResponseEntity

2023-04-08 01:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingService.java
> +        Random random = new Random();
`keyword` Random 객체는 이 메서드가 호출될떄마다 재생성 됩니다.

2023-04-08 01:33 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/service/BattingService.java
> +        }
값을 생성하기 위한 판단을 위임할 수 있지 않을까요?

2023-04-12 02:44 UTC, Hyune-c requested changes

2023-04-12 02:44 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
>      }
Math 로 계산하기보다는 assert 문을 더 잘 활용하는 방법을 생각해주세요.

```java
    assertThat(5.0).isCloseTo(6.0, withinPercentage(20.0));
    assertEquals(2.5, 2.4, 0.11);
```

2023-04-12 02:44 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        Assertions.assertTrue(validResult);
`nit` 
- 개인적으로는 assertThat() 으로 시작해 빌더 형태로 선언하는 것을 선호합니다.
- Assertions 는 static import 를 추천합니다.

2023-04-12 02:44 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/common/RandomUtils.java
> +}
- util 은 bean 이어야 할까요?

생성자를 제외한 메서드와 변수를 모두 static 으로 구현해 놓으셨습니다.

2023-04-12 02:44 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/common/RandomUtils.java
> +    private static final Random random = new Random();
static final 은 대문자로 네이밍 해주시는 것이 컨벤션 입니다.

2023-04-12 09:32 UTC, Jungeunkim-dev commented on src/main/java/com/hyunec/cosmicbaseballinit/common/RandomUtils.java
> +    private static final Random random = new Random();
> The names of variables declared class constants and of ANSI constants **should be all uppercase** with words separated by underscores ("_"). (ANSI constants should be avoided, for ease of debugging.) 
_JAVA 9 - Naming Conventions_

static final 변수 관련한 네이밍 컨벤션은 처음 알게 되었습니다.
대문자 네이밍으로 수정했습니다.

2023-04-12 14:04 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/common/RandomUtils.java
> +    private static final Random random = new Random();
https://google.github.io/styleguide/javaguide.html

그다지 길지 않고, 사설 한글 번역본도 많으니 이것도 한번 참고하시면 좋을 것 같습니다.

https://naver.github.io/hackday-conventions-java/

네이버도 있습니다.

2023-04-13 06:02 UTC, Jungeunkim-dev commented on src/main/java/com/hyunec/cosmicbaseballinit/common/RandomUtils.java
> +}
랜덤 타격값을 반환하는 로직은 전체 서비스 로직 상에서 공통적으로 사용될 것이라 생각해서 utility 클래스로 분리했었는데요. 코멘트를 보고 찾아본 결과 [static으로 등록 / bean으로 관리] 선택에 대해 여러 자료가 있어 조사해 보았습니다.

결론적으로는 현재 RandomUtils 내의 `getRandomBattingResult`는 외부 자원에 의존하지 않아서, bean으로 등록하지 않고 static으로 선언하는 것이 더 적합하다고 생각합니다. 또한 이후로도 RandomUtils에 외부에 종속되지 않는 메소드들을 추가하면 bean 등록 없이 사용할 수 있을 듯 합니다. 

정리하자면,
- configuration, DB 상태와 관련없이 인자가 동일할 때 항상 같은 결과를 리턴한다면, static으로 구현합니다.
- 그렇지 않다면, bean으로 등록해서 spring에서 관리합니다.

2023-04-13 09:19 UTC, Hyune-c approved these changes
리뷰 내용이 좀 더 남았지만 너무 길어진다고 생각하여 내용을 정리해드리고 approve 하였습니다.

2023-04-13 09:19 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/acceptancetest/NormalBaseballLv1Test.java
> +        assertThat(count).isCloseTo(33333, Percentage.withPercentage(5));
```suggestion
        assertThat(count).isCloseTo(caseSize/3, Percentage.withPercentage(5));
```

`nit` 
보통 매직 넘버는 사용을 지양하는 것을 추천합니다.
하지만 예외적으로 테스트 코드에서는 어느정도 재사용성을 포기하거나, 매직 넘버를 써도 좋다고 생각합니다.

2023-04-13 09:19 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/common/RandomUtils.java
> +}
이번 PR 에서 가장 많은 리뷰를 받은 부분이군요.
리뷰 드렸던 내용을 되짚어보면서, 리뷰 의도를 전달드리고 마무리 하겠습니다.

> Random 객체는 이 메서드가 호출될떄마다 재생성 됩니다.

- Spring 은 대량 처리에 특화된 EE 웹 프레임워크입니다. 
    - 따라서 메서드가 호출될 때마다 Random 객체를 생성하는 것은 적절하지 않습니다.
- 특히 Random 함수의 경우 java 는 객체를 생성해야되지만, kotlin 에서는 object class 이기에 공통으로 사용할 수 있습니다. 

> util 은 bean 이어야 할까요?

- util 이란 네이밍을 쓰실 때는 부수 효과가 없어야 되는 FP 를 (함수형) 생각하면 좋다고 생각합니다.

> 그 외

- `NoArgsConstructor` 는 매개변수가 없는 생성자를 만드는 lombok annotation 입니다.
    - 이 클래스에 생성자가 필요한가요?
- 클래스 네이밍은 완전히 common 한 형태입니다.
    - 하지만  메서드인 `getRandomBattingResult` 는 비즈니스 요구 사항을 표현하고 있습니다.
- `getRandomBattingResult` 는 BattingResult 의 생성 책임을 가지고 있습니다.
    - util 이 생성 책임을 가지고 있는 것이 적절할까요?
    - factory 패턴을 차용할 수도 있고, BattingResult 내로 응집시킬 수도 있습니다.

2023-04-14 11:24 UTC, merged