야구 1단계 PR요청드립니다.
Programmers-Hyune-c/cosmic-baseball-init pull request #7
Opened 2022-12-07 01:50 UTC by shinseongsu

안녕하세요 이번에 수업듣게된 신성수입니다.
미천한 코드이지만 잘부탁드립니다. 😢 

## 기능 구현

- [x] 즉시 아웃되는 bullseye strike 추가 (strike 의 20%)
- [x] 즉시 출루되는 bullseye ball 추가 (ball 의 20%)
- [x] 즉시 득점되는 homerun 추가 (hit 의 20%)

## 개발자의 의도

개인적으로 domain이라고 패키지를 나누기 보다는 어떤 도메인에서 ui, domain, application 같은 걸로 나누고 싶어 구조를 수정하였습니다.
나중에 DB가 연결이 된다고 한다면 Repository나 Service와 같이 일반적으로 사용되는 구조들이 편하다고 생각하였습니다.

2022-12-07 01:53 UTC, shinseongsu commented
리뷰어 할당이 안되어서 혹시 할당 직접 지정해주실수 있으실까요? ㅠㅠ

![image](https://user-images.githubusercontent.com/24979159/206068157-cffccd5a-9598-4f8a-bd1e-14fc2a56cac4.png)

2022-12-07 03:39 UTC, Hyune-c requested changes
리뷰를 하다보니까 벌써 우주야구 1단계의 것이 구현되어있네요..
Mandantory 를 확인해주세요.
- 본 리뷰는 중간에 멈추었습니다.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/55722186/206082355-64a9de05-cf09-4e17-b42c-280f4f2bfae2.png">

2022-12-07 03:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +        }
문맥상 `isClear()` 가 true 이면 이미 clear 된 상태로 읽힙니다.
하지만 로직은 이미 클리어된 상태여도 clear 하게 되어 있습니다.

2022-12-07 03:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRepository.java
> +public interface BattingRepository {
벌써 영속성 영역 교체에 대한 고민을 하고 있으시다니 대단하네요. 👍

2022-12-07 03:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingReposityImpl.java
> +        return List.copyOf(battingList);
방어적 복사의 활용 좋습니다. 👍

2022-12-07 03:44 UTC, shinseongsu commented
@Hyune-c  제가 잘 이해를 했는지 혹시 확인해주실수 있을까요?
- 일반야구가 진행되는 로직을 먼저 만든후, 1단계를 실행하는게 맞을까요?

2022-12-07 04:03 UTC, Hyune-c commented
> @Hyune-c 제가 잘 이해를 했는지 혹시 확인해주실수 있을까요?
> 
> * 일반야구가 진행되는 로직을 먼저 만든후, 1단계를 실행하는게 맞을까요?
> * 예를 들어,  1단계 일반야구 로직이 밑에와 같다면,
> 
> ```
> - 선수는 1명으로 타자로만 플레이 합니다.
> - 스트라이크, 볼, 안타은 같은 확률을 가집니다.
> - 1개의 게임은 1개의 타석으로 구성 됩니다.
> ```
> 
> 이거를 먼저 PR를 받고
> 
> ```
> - 즉시 아웃되는 bullseye strike 추가 (strike 의 20%)
> - 즉시 출루되는 bullseye ball 추가 (ball 의 20%)
> - 즉시 득점되는 homerun 추가 (hit 의 20%)
> ```
> 
> 를 진행하면 되는걸까요?

네 그렇습니다. readme 를 좀 더 보강했습니다.

![image](https://user-images.githubusercontent.com/55722186/206085389-b143c233-fec1-44a1-9ee8-d301f31b2852.png)

2022-12-07 12:00 UTC, shinseongsu commented
## 기능구현

- [x] 선수는 1명으로 타자로만 플레이 합니다.
- [x] 스트라이크, 볼, 안타은 같은 확률을 가집니다.
- [x] 1개의 게임은 1개의 타석으로 구성 됩니다.

## 수정사항

- 우주 미션1단계 한꺼번에 해서 일반 야구 1미션으로 수정하였습니다.

> 문맥상 `isClear()` 가 true 이면 이미 clear 된 상태로 읽힙니다. 하지만 로직은 이미 클리어된 상태여도 clear 하게 되어 있어 혼동을 줍니다.

isClearable 이라는 단어로 썼는데 제 예상으로는 clear될수 있는 으로 사용하였습니다.

2022-12-07 12:01 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +        }
음.. 좀더 명확한 메소드명 생각하겠습니다 😢

2022-12-07 12:59 UTC, Hyune-c requested changes
코멘트가 너무 많아져서 1차 수정 후 추가 리뷰 하겠습니다.

- 랜덤 테스트를 위해 stub 을 쓰신 것은 훌륭합니다.
    - 하지만 고정 값을 반환하게 만든 순간 random 이 사라짐으로 네이밍이 필요할 듯 합니다.
    - generate() 의 값이 각각 0, 1, 20 인데 저는 이 의미를 쉽게 짐작할 수 없습니다. 명시적이지 않습니다.
- application 과 domain 패키지를 나누고 service 를 application 에 두셨네요.
    - 그렇다면 service 에는 도메인 로직이 있으면 안된다고 생각합니다. 하지만 `배팅들을 클리어하기 위한 판단 로직`이 들어가 있습니다.

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +    }
클래스명에 따르면 이 클래스는 `Batting` 을 랜덤하게 생성하는 역할을 할 것 같습니다.
그런데 generate 의 결과가 int 이어도 괜찮을까요?

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    }
`nit` 
상극의 역할을 하는 메서드가 각각 존재해야 될까요?
특히 `isEmpty()` 는 이 클래스 내에서만 사용되는 것 같습니다.

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
enum.name(), 부정, & 연산자의 콜라보라니.. 다행히 가독성을 엄청 해치지는 않지만 조금 더 개선할 수 있다고 생각합니다.
메서드의 조건에 맞는 enum list 를 가지고 있는 방법은 어떨까요?

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
`nit` enum.valueOf() 의 활용은 어떨까요?

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    FOUR_BALL(4),
아웃과 포볼은 배팅의 결과일까요?
저는 타석의 결과, 또는 배팅들의 결과라고 생각하는데 어떻게 생각하시나요?

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +        }
네이밍을 볼 때 `클리어 가능한 배팅인가?` 를 물어보고 있습니다.
그리고 클리어하고 있습니다.
그렇다면 클리어 가능한 경우에는 무조건 클리어 되는 것인데 `클리어 해야 되는가?` 에 대한 의문은 필요 없나요?

메시지를 던지는 것이 아닌, 상태를 묻고 변경시킨다는 느낌이 듭니다.

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Batting.java
> +    }
enum 생성에 랜덤 전략을 주입하다보니 복잡해지는 것 같습니다.
차라리 생성 책임을 분리한 factory 를 만드는건 어떨까요?

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +    public BattingResult swing(Batting batting, RandomGenerate randomGenerate) {
batting 과 swing 은 사실상 같은 표현 같습니다.
굳이 구분한 이유가 있을까요?

2022-12-07 12:59 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingServiceTest.java
> +    }
여러 테스트에서 generate 를 오버라이드 하고 계시네요.
그런데 저는 리뷰어의 시선에서 볼 때 0, 1, 20 의 뜻이 와닿지 않습니다.

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    }
숫자를 세고 싶으신 것이라면 `count()` 를 활용하는 것이 더 좋을 것 같습니다.

2022-12-07 12:59 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    private final RandomGenerate randomGenerate;
Battings 는 배팅 결과의 스냅샷을 가지는 일급 컬렉션을 의도한 것으로 보입니다.
그렇다면 랜덤 제네레이트를 가져야되는 이유가 있나요?

2022-12-07 14:22 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +    }
BattingRandomGenerate 이기때문에 int 보다는 Batting을 반환하는데 더 좋을것같다는 말씀이실까요?

2022-12-07 14:25 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    }
습적으로 상극을 만들어 낸것같네요 중복이 되는점이 있어서 만들어 두면 언젠가 쓰겠지 하고 만들었었네요 😢

2022-12-07 14:26 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
ㅠㅠ 미천한 코드라 죄송합니다.
조건 EnumSet이나 list로 만들어 체크하겠습니다

2022-12-07 14:27 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
저 메소드를 몰랐어요  👍

2022-12-07 14:28 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    FOUR_BALL(4),
OUT은 스트라이크 3번에 발동한다. 라고 표현하고 싶었는데 표현력이 아쉬웠네요 ㅠㅠ

2022-12-07 14:39 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +        }
좀더 표현력있게 수정하겠습니다 😄

2022-12-07 14:43 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +    public BattingResult swing(Batting batting, RandomGenerate randomGenerate) {
service에서는 여러가지 행동들이 추가될것같아서 비슷하지만 다른 메소드 명으로 사용했었습니다.

2022-12-07 14:43 UTC, shinseongsu commented on src/test/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingServiceTest.java
> +    }
아하 그렇군요 넘버 상수 이용하여 표현하도록 하겠습니다

2022-12-07 14:48 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    private final RandomGenerate randomGenerate;
battingResult를 결과로 반환할때, 매개변수가 많아지는 느낌이 들어서 생성자할때 같이 넣었는데, Batting의 일급 객체니깐, 하나의 책임만 가지는게 좋을까요?

2022-12-07 15:13 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +    }
네 그렇습니다. 
개발한 사람이야 저 int 가 Batting 으로 변환되는 과정을 알고 있기에 잘 쓸 수 있다지만.
처음 보는 사람 입장에서는 `Batting 을 generate 한다고 해놓고 뜬금없이 int 가 나오니` Batting 으로 연결할 수 없습니다.

2022-12-07 15:13 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    FOUR_BALL(4),
네. `한번의 배팅의 결과`인 스트라이크, 볼, 히트와 `배팅들의 결과`인 아웃과 포볼은 동일 선상에 있어서는 안된다고 생각합니다.
어쩌면 히트도 배팅들의 결과로 가야될 수도 있겠네요.

2022-12-07 15:13 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
미천한 코드라고는 표현하지 않아도 괜찮아요. 
충분히 좋은 코드들을 작성하고 계십니다. 👍

2022-12-07 15:13 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    private final RandomGenerate randomGenerate;
Battings 는 Batting 의 리스트를 가지고 있는 일급 컬렉션 아닌가요?
일급 객체와 일급 컬렉션은 다른 개념입니다.

---

다른 것을 떠나 randomGenerate 가 본 클래스 내에서 쓰이지 않습니다.
그렇다면 다른 곳에서 쓰더라도 getter 형태로 가져갈 수 밖에 없게 됩니다.

`객체에게 메시지를 전달하라` 와 상반됩니다.

2022-12-07 16:26 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/Battings.java
> +    private final RandomGenerate randomGenerate;
아하 randomGenerate 가 우주미션때 쓰이던걸 다 못지웠었네요

일급객체 : 일급객체(First-class Object)란 다른 객체들에 일반적으로 적용 가능한 연산을 모두 지원하는 객체를 가리킨다
일급 컬렉션: 콜렉션을 포함한 클래스는 반드시 다른 멤버 변수가 없어야 한다. 각 콜렉션은 그 자체로 포장돼 있으므로 이제 콜렉션과 관련된 동작은 근거지가 마련된셈이다.

아 다른 의미였네요 잘못된점 집어주셔서 감사합니다.

2022-12-09 14:10 UTC, shinseongsu commented
## 수정 점

- BattingRandomGenerate 에서 Batting 반환하게 수정
- 일급콜렉션에 있던 RandomGenerate 삭제
- 타석 결과와 배팅 결과를 분리

## 코멘트

제가 잘못 이해한점이 있으면 매운맛으로 코멘트 주시면 감사하겠습니다.
늦게 제출해서 죄송합니다. 😢

2022-12-09 14:39 UTC, Hyune-c approved these changes
> 제가 잘못 이해한점이 있으면 매운맛으로 코멘트 주시면 감사하겠습니다.
늦게 제출해서 죄송합니다. 😢

이 교육은 본인의 페이스대로 진행하는 교육이니 제출에 스트레스 받지 않으셔도 됩니다.
충분히 잘하고 계세요. 👍

---

enum.name() 을 많이 활용하시다보니 string 으로 노출되는 부분이 많은 것 같습니다.
조금 더 안전한 코딩을 위해서는 enum 을 더 활용해주시면 좋을 것 같습니다.

2022-12-09 14:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingService.java
> +    }
- swing 의 결과가 battingResult 라는 `의미 있는 타입` 이라면 string 은 인적 실수의 여지가 있을 것 같습니다.

`nit` 
- battings.battingResult() 는 뭔가 중복되는 것처럼 보이네요. battings.result() 로 수정할 수 있을 듯 합니다.
    - 하지만 이렇게 바꾸면 의도한 battingResult 가 아닌 battingsResult 가 나올 것 같아 더 애매해질 수 있습니다.
- batting 결과는 이전 battings 들과 관계가 있음으로 지금도 나쁘지 않습니다.
    - 하지만 battingResult 를 계산해주는 컴포넌트를 별도로 두는 방법도 있습니다.
    - 지금까지의 battings 와 새로운 batting 을 받아 계산하는 방법이 있겠죠.
    - 이렇게 한다면 save 를 먼저 하고 시작하지 않아도 될 것입니다.
- db 연결까지를 고려한다면 지금 이 메서드는 save 를 먼저 시작함으로 인해 transaction 의 범위가 큽니다.

2022-12-09 14:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/RandomGenerate.java
> +}
`nit` 
테스트까지의 의도를 보면 `랜덤 배팅 결과 생성기` `고정 배팅 결과 생성기` 를 의도하신 것 같습니다.
그렇다면 interface 는 RandomGenerate 보다는 BattingGenerator 가 좀 더 공통 관심사를 표현하는 것이라고 생각합니다.

2022-12-09 14:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +        }
ordinal 사용의 위험함을 알고 계신가요?

2022-12-09 14:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    private static final Set<String> CONTINUE_PLAY = Set.of(STRIKE.name(), BALL.name());
👍

2022-12-09 14:39 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
```java
    public boolean isFinishPlaceApperances(final String battingResult) {
        return !BattingResult.isNotFinishBaseBall(battingResult);
    }
```

이 메서드가 쓰이는 곳을 보니 부정문으로 활용하고 계시네요.
is 로 시작하는 메서드문는 보통 긍정문이 가독성이 좋은 경우가 많습니다.

처음부터 메서드를 긍정문으로 표현하는 것은 어떨까요?

2022-12-09 14:39 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingServiceTest.java
> +    Batting[] battings;
성능이 극도로 필요한 경우가 아니라면 java collection 의 활용을 권장합니다.

2022-12-09 14:39 UTC, Hyune-c commented on src/test/java/com/hyunec/cosmicbaseballinit/hitter/application/BattingServiceTest.java
> +    }
`nit` BDD 스타일을 활용해보는 것도 좋습니다.

2022-12-10 02:36 UTC, shinseongsu commented
@Hyune-c  질문 있습니다. 
현재 배팅 결과(battingResult)와 배팅들의 결과(battingsResult)으로 나눴는데 둘다 타입이 달라 반환값을 string으로 나타냈습니다.

이렇게 enum값이 나눠져있을때, 반환값을 안전하게 enum으로 하고 싶은데 힌트를 주실 수 있을까요?

2022-12-10 04:51 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/RandomGenerate.java
> +}
아하 그렇군요 저는 처음에 batting을 위한 랜덤값만 생성하는 목적으로 만들었어서 관심사가 달라지니 네이밍도 달라져야 이해하기 쉽겠군요

2022-12-10 04:52 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +        }
https://duzi077.tistory.com/235

이펙티브 자바에서 설명하듯이 ordinal을 사용하다가 순서가 변경되면 예상치못한 결과가 나오기 떄문에 사용하지 말라고 되어 있군요
상수 필드를 추가하여 사용하도록하겠습니다

2022-12-10 04:52 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingResult.java
> +    }
아하 그렇군요 긍정문으로 표현하도록하겠습니다

2022-12-10 06:49 UTC, Hyune-c commented
> 현재 배팅 결과(battingResult)와 배팅들의 결과(battingsResult)으로 나눴는데 둘다 타입이 달라 반환값을 string으로 나타냈습니다.
이렇게 enum값이 나눠져있을때, 반환값을 안전하게 enum으로 하고 싶은데 힌트를 주실 수 있을까요?

하나의 swing 에서 서로 다른 type 이 나올 수 있는 지금의 구조라면 string 으로 할 수 밖에 없겠네요.
super type, sub type 을 사용하는 방법도 있겠지만 너무 복잡해질 것 같네요.
이번의 목표는 달성 하셨으니 다음 버전에 리팩토링 하는 것을 추천합니다.

---

도메인 로직에 대한 생각은 개인마다 다르겠지만 저는 아래와 같이 생각합니다.

- 배팅 그 자체만이 도메인 로직이다.
- 배팅의 결과는 표현 레이어의 역할이다.

2022-12-10 08:25 UTC, Hyune-c commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +        final int randomValue = random.nextInt(BATTING_CASE_COUNT);
`random.nextInt(BATTING_CASE_COUNT)` 로 2가 나올 수 있나요?

2022-12-10 08:57 UTC, shinseongsu commented on src/main/java/com/hyunec/cosmicbaseballinit/hitter/domain/BattingRandomGenerate.java
> +        final int randomValue = random.nextInt(BATTING_CASE_COUNT);
코틀린 range에서는 끝범위까지 나왔는데, 자바는 끝자리는 미만 범위까지 나오는군요

2022-12-10 10:12 UTC, shinseongsu commented
## 수정점

- strike, ball 카운트 구하는 stream 에서 reduce보다 count 사용
- BattingGenerate 로 이름 수정
- 랜덤 카운트 범위 올리기
- 긍정적인 메소드로 수정하기
- 타석결과를 구하는 component 새로 만들기

## 궁금한점

- Controller를 테스트하고 싶은데, 많이 mockMvc를 사용하는데 저는 RestAssured가 API테스트하는데 더 편한것같아서 이 라이브러리를 사용해도 될까요?

2022-12-10 10:26 UTC, Hyune-c approved these changes
> Controller를 테스트하고 싶은데, 많이 mockMvc를 사용하는데 저는 RestAssured가 API테스트하는데 더 편한것같아서 이 라이브러리를 사용해도 될까요?

네.

2023-01-04 15:32 UTC, Hyune-c commented
더 이상 진행이 없어 이슈를 종료 합니다.

2023-01-04 15:32 UTC, closed without merging